<div class="home-content-box">
    <h2 class="lead">Codexplo 2.0 - Ricerca nei grandi commentari del CC e del C0</h2>
    <p>
        Codexplo permette la ricerca degli articoli nei grandi commentari del CC e del CO (Basler Kommentar, Berner Kommentar, Commentaire romand, Zürcher Kommentar). E' dunque possibile identificare con pochi clic i tomi che commentano un determinato articolo
    </p>
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://lawlibraries.ch/?page_id=1060&lang=fr') ?>" target="_blank"
       class="btn btn-link" title="Link zu Codexplo">Codexplo 2.0</a>
</div>

