<div class="home-content-box">
    <h2 class="lead">A proposito di jusbib</h2>
    <p>
        jusbib è un meta-catalogo da biblioteche giuridiche svizzere ed altre collezioni giuridici.
        L'interfaccia e le funzionalità di ricerca di jusbib corrispondono a quelle di swissbib.
    </p>
    <a href="<?= $this->basePath('Libraries') ?>" class="btn btn-link" title="Istituzione">Istituzione participante</a>
</div>
