<div class="home-content-box">
    <h2 class="lead">A proposito di jusbib</h2>
    <p>
        Jusbib è un meta-catalogo di dati bibliografici provenienti da biblioteche giuridiche svizzere ed altre collezioni
        di dati giuridici. L'interfaccia e le funzionalità di ricerca di jusbib corrispondono a quelle di Swissbib.
    </p>
    <a href="<?= $this->basePath('Libraries') ?>" class="btn btn-link" title="Istituzione">Istituzioni partecipanti</a>
</div>
