<div class="home-content-box">
    <h2 class="lead">Codexplo 2.0</h2>
    <p>Ricerca degli articoli nei grandi commentari al CC ed al CO</p><br/>
        <p>Codexplo permette la ricerca degli articoli nei grandi commentari del CC e del CO (Basler Kommentar, Berner Kommentar, Commentaire romand, Zürcher Kommentar) ed offre così la possibilità d’identificare e localizzare rapidamente i diversi volumi che commentano un determinato articolo.</p>
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://lawlibraries.ch/?page_id=1060&lang=fr') ?>" target="_blank"
       class="btn btn-link" title="Link zu Codexplo">Codexplo 2.0</a>
</div>

