<div class="home-content-box">
    <h2 class="lead">Nuovo design 2015</h2>
    <p>
        jusbib cambia veste questa primavera. Il design reattivo si adatta dinamicamente alla grandezza dello schermo.
        E’ dunque possibile utilizzare jusbib senza limitazioni con lo smartphone, con il tablet oppure con il PC.
    </p>
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.swissbib.blogspot.ch/') ?>" target="_blank"
       class="btn btn-link" title="Blog">Altre info</a>
</div>

