<div class="home-content-box">
    <h2 class="lead">Manuscripts and archival collections</h2>
    <p>
        With the partial integration of the <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/han/') ?>"
        target="_blank">network "Handschriften, Archive, Nachlässe" (HAN)</a>, swissbib simplifies the discovery
        of additional archival collections as well as digitised manuscripts and other unique documents.
    </p>
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.swissbib.blogspot.ch/') ?>"
       target="_blank" class="btn btn-link" title="Link zum Blog">Additional information</a>
</div>

