<div class="home-content-box">
    <h2 class="lead">National Licences</h2>
    <p>
        Access to the complete journal archives of Cambridge University Press, de Gruyter and Oxford
        University Press is open to the general public in Switzerland. More than two million articles
        from 1770 to 2015 are freely available.
    </p>
    <p>
        <a href='/Search/Results?type=AllFields&filter[]=union%3A"NATIONALLICENCE"'>Search the archives</a>
        via swissbib and register for free access.
    </p>
    <a href="http://swissbib.blogspot.ch/2016/12/more-than-two-million-scientific.html"
       class="btn btn-link" title="Link to blog post">Additional information</a>
</div>