<div class="home-content-box">
    <h2 class="lead">HelveticArchives</h2>
    <p>
        HelveticArchives, the database for the archival collections of the Swiss National Library, has been updated in
        swissbib. Thousands of digitised photographs from the Prints and Drawings Department and the Swiss Literature
        Archive are accessible and linked with their respective collection records.
    </p>
    <a href="<?= $this->basePath('Search/Results?type=AllFields&filter[]=union%3A%22CHARCH%22') ?>"
       target="_blank" class="btn btn-link" title="Link to the collections">All documents</a>
</div>