<?
/** @var VuFind\RecordDriver\SolrDefault $record */
$record         = $this->driver;
/** @var Swissbib\View\Helper\Record $viewRecord */
$viewRecord     = $this->record($record);

$id                   = $record->getUniqueId();
$shortTitle           = $record->getShortTitle();
$titleStatement       = $record->getTitleStatement(true);
$subtitle             = $viewRecord->getSubtitle($titleStatement);
$responsible          = $viewRecord->getResponsible($titleStatement, $record);
$publications         = $record->getPublicationDetails();
$physicalDescriptions = $record->getPhysicalDescriptions(false);
$edition              = $record->getEdition();
$cartMathData         = $record->getCartMathData();
$formats              = $viewRecord->getFormatList();
$hierarchicalLevel    = $record->getHierachicalLevel();
$hostItems            = $record->getHostItemEntry();
$journalTitle         = $record->getContainerTitle();
$ref                  = $record->getContainerReference();
$highlightedFulltext  = $record->getHighlightedFulltext();

$showFRBR = $this->configAccess()->Site->displayFrbr;
$groupID  = $this->driver->getGroup(true);

$urls = $viewRecord->getExtendedLinkDetails();
$link360 = $viewRecord->getLink360();
$linkSFX = $viewRecord->getLinkSFX();

?>

<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">

  <div class="col-sm-3 hidden-xs">
    <div class="thumbDetailView hidden-print">
      <? /* Display thumbnail if appropriate: */ ?>
      <? $mediumThumb = $viewRecord->getThumbnail('medium'); ?>
          <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtmlAttr($mediumThumb);?>"/>

      <? /* Display qrcode if appropriate: */ ?>
      <? $QRCode = $viewRecord->getQRCode("core"); ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <? // if you have a preview tab but want to move or remove the preview link
    // from this area of the record view, this can be split into
    // getPreviewData() (should stay here) and
    // getPreviewLink() (can go in your desired tab) ?>
    <?=$viewRecord->getPreviews()?>
  </div>

  <div class="col-sm-9 col-xs-12">
    <h3 property="name"><?=$this->escapeHtml($shortTitle)?></h3>
    <? if (isset($subtitle)): ?>
      <h4 class="resultViewSubTitle"><?= $this->escapeHtml($subtitle) ?></h4>
    <? endif; ?>

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hidden alert alert-info" id="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>

    <?/* Display Main Details */?>
    <div class="meta" summary="<?=$this->transEsc('Bibliographic Details')?>">
    <? if (!empty($responsible)): ?>
        <!-- Verfasser / Beitragende -->
        <span class="label"><?=$this->transEsc('Author')?>:</span>
        <span><?=$this->escapeHtml($responsible)?></span><br />
    <? endif; ?>

    <!-- Impressum -->
    <? if (!empty($publications)): ?>
      <span class="label"><?=$this->transEsc('Publication')?>: </span>
      <span>
          <? foreach ($publications as $field): ?>
              <span property="publisher" typeof="Organization">
                  <? $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
                      <span property="location"><?=$this->escapeHtml($pubPlace)?> :</span>
                  <? endif; ?>
                  <? $pubName = $field->getName(); if (!empty($pubName)): ?>
                      <span property="name"> <?=$this->escapeHtml($pubName)?>, </span>
                  <? endif; ?>
              </span>
              <? $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
                  <span property="publicationDate"><?=$this->escapeHtml($pubDate)?></span>
              <? endif; ?>
              <? if(!next($publications) === false){echo('<br />');} ?>
          <? endforeach; ?>
      </span><br />
    <? endif; ?>

    <? if (!empty($journalTitle)): ?>
      <span class="label"><?=$this->transEsc('Journal Title')?>:</span>
      <span>
        <?=$this->escapeHtml($journalTitle) . ',' . ' '?>
        <? if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
      </span><br />
      <? endif; ?>

      <? if ($hostItems): ?>
      <span class="label"><?= $this->transEsc('note_773') ?>: </span>
      <span>
          <? foreach ($hostItems as $hostItem): ?>
              <? $text = isset($hostItem['title']) ? ( array_key_exists('related', $hostItem) ? $hostItem['title'] . ', ' . $hostItem['related'] : $hostItem['title'] ) : '' ?>
              <?= $this->escapeHtml($text) ?><br />
          <? endforeach; ?>
      </span><br />
      <? endif; ?>

      <?php if ($cartMathData): ?>
        <span class="label"><?= $this->transEsc('Map_Scale') ?>:</span>
        <span><?= $this->escapeHtml($cartMathData) ?></span><br />
      <?php endif; ?>

      <?php if ($physicalDescriptions): ?>
        <span class="label"><?= $this->transEsc('Physical Description') ?>:</span>
        <span><?= $this->physicalDescription($physicalDescriptions) ?></span><br />
      <?php endif; ?>

      <? if (!empty($formats)): ?>
        <span class="label"><?=$this->transEsc('Format')?>: </span>
        <span><?= $formats ?></span><br />
      <? endif; ?>

      <? if (!empty($hierarchicalLevel)): ?>
          <span class="label"><?=$this->transEsc('hierarchical_level')?>: </span>
          <span><?= $this->zendTranslate($hierarchicalLevel, 'formats') ?></span><br />
      <? endif; ?>

      <? if (!empty($edition)): ?>
        <span class="label"><?=$this->transEsc('Edition')?>: </span>
        <span property="bookEdition"><?=$this->escapeHtml($edition)?></span><br />
      <? endif; ?>



      <? if (T_TRUE): ?>
        <span class="label">Test URL: </span>
        <span>

            <?

            $gruyterBaseUrl="https://www.degruyter.com/openurl?genre=article";
            $cambridgeBaseUrl="http://www.cambridge.org/core/product/identifier/";
            $cambridgeEndUrl="/type/JOURNAL_ARTICLE";
            $oxfordUrlPart1="http://";
            $oxfordUrlPart2=".oxfordjournals.org/content/";




            /*$marcField949=$record->getMarcSubFieldMaps(
                949, [
                'B' => 'publisherSource'
            ]);
            $publisherSource=$marcField949["publisherSource"];
            echo $publisherSource;*/
            #$tests=$record->get950();
            #echo $tests["union"];
            #$tests=$record->getMarcRecord()->getFields('949');
            #print_r($tests);
            #echo $tests[0]->getSubfield('b');



            $publisherSource="";

            #for testing : use of the id to know the source
            #instead need to read 949$b
            switch($id) {
                case "NLgruyter":
                    $publisherSource="NL-gruyter";
                    break;
                case "NLoxford":
                    $publisherSource="NL-oxford";
                    break;
                case "NLcambridge":
                    $publisherSource="NL-cambridge";
            }





            switch($publisherSource) {
                case "NL-gruyter":
                    #https://www.degruyter.com/openurl?genre=article&issn=2191-4664&volume=106&issue=6&spage=122
                    $issn=$hostItems[0]["issn"];
                    $enumeration=$hostItems[0]["enumeration"];
                    $splitted=explode(":",$enumeration);
                    $volume=$splitted[0];
                    $issuePage=explode("<",$splitted[1]);
                    $issue=$issuePage[0];
                    $spage=$issuePage[1];
                    echo $gruyterBaseUrl."&issn=".$issn."&volume=".$volume."&issue=".$issue."&spage=".$spage;
                    break;
                case "NL-oxford":
                    #http://nar.oxfordjournals.org/content/25/17/3389.long
                    #http://JOURNALCODE.oxfordjournals.org/content/VOLUME/ISSUE/PAGE.long
                    $journalCode="nar"; #needs to be added to cbs
                    $enumeration=$hostItems[0]["enumeration"];
                    $splitted=explode(":",$enumeration);
                    $volume=$splitted[0];
                    $issuePage=explode("<",$splitted[1]);
                    $issue=$issuePage[0];
                    $spage=$issuePage[1];
                    echo $oxfordUrlPart1.$journalCode.$oxfordUrlPart2.$volume."/".$issue."/".$spage.".long";

                    break;
                case "NL-cambridge":
                    #http://www.cambridge.org/core/product/identifier/S0024282914000401/type/JOURNAL_ARTICLE
                    #http://www.cambridge.org/core/product/identifier/ARTICLE_IDENTIFIER/type/JOURNAL_ARTICLE
                    $doi=$record->getDOIs()[0];
                    #for 10% of articles, this doesn't work, the part after the / is not the cambridge article identifier
                    $article_id=explode("/",$doi,2)[1]; #everything after the first / in doi
                    echo $cambridgeBaseUrl.$article_id.$cambridgeEndUrl;
                    break;
            }


            ?>
        <br /></span>
      <? endif; ?>



      <? if (!empty($urls)): ?>
        <span class="label"><?=$this->transEsc('Online Access')?>: </span>
        <span><br />
          <? foreach ($urls as $current): ?>
            <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($this->redirectProtocolWrapper()->getWrappedURL($current['url'])))?>" target="_blank" title="<?=$this->escapeHtml($current['desc'])?>">
                <?=$this->escapeHtml($current['desc'])?>
            </a><br/>
          <? endforeach; ?>
          <? if ($linkSFX): ?>
            <?= $linkSFX ?><br/>
          <? endif; ?>
        </span><br />
      <? endif; ?>

      <? if (!empty($link360) || $linkSFX): ?>
         <span class="label"><?= $this->transEsc('Online Access') ?>: </span>
         <span><br />
        <a title="<?= $this->transEsc('articles.link360') ?>" class="linkbutton primary icon_link_primary"
           target="_blank" href="<?= $link360 ?>">get&#160;it</a><br/>
        <?=$linkSFX ?></span>
        <br/>
      <? endif; ?>

      <?php if ($id): ?>
        <span class="label visible-print-inline"><?= $this->transEsc('Item_ID') ?>:</span>
        <span class="visible-print-inline"><?= $id ?></span>
      <?php endif; ?>

      <?php if (!empty($showFRBR) && $showFRBR && !empty($groupID)) : ?>
       <span class="hidden-xs">
         <a href="<?=
          $this->url('search-results') . '?lookfor=' . $groupID . "&type=FRBR&sort=publishDateSort+desc" ?>"
             class="btn btn-primary icon_show" title="<?= $this->transEsc('Other Editions') ?>">
              <span><?= $this->transEsc('Other Editions') ?></span>
          </a>
       </span><br />
      <?php endif; ?>
        <?php if ($highlightedFulltext): ?>

                <span class="label"><?= $this->transEsc('fulltexthighlight') ?>: </span>
                <span><br />
                <?= $this->highlight($highlightedFulltext) ?></span>

        <?php endif; ?>

    </div>
    <?/* End Main Details */?>
  </div>
</div>