<div class="home-content-box">
    <h2 class="lead">Codexplo 2.0</h2>
    <p>Suche in den Grosskommentaren ZGB/OR </p><br/>
        <p>Codexplo ermöglicht die Suche nach Artikeln in den ZGB/OR-Grosskommentaren (Basler Kommentar, Berner Kommentar, Commentaire romand, Zürcher Kommentar) und somit die schnelle Identifikation und Standortbestimmung der verschiedenen Bände, die einen bestimmten Artikel kommentieren.
    </p>
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://lawlibraries.ch/?page_id=1060&lang=fr') ?>" target="_blank"
       class="btn btn-link" title="Link zu Codexplo">Codexplo 2.0</a>
</div>

