<div class="home-content-box">
    <h2 class="lead">Codexplo 2.0 - Suche in den Grosskommentaren ZGB/OR</h2>
    <p>
        Codexplo ermöglicht die Suche nach Artikeln in den Grosskommentaren ZGB/OR (Basler Kommentar, Berner Kommentar, Commentaire romand, Zürcher Kommentar) und die schnelle Identifikation der verschiedenen Bände, die einen bestimmten Artikel kommentieren.
    </p>
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://lawlibraries.ch/?page_id=1060&lang=fr') ?>" target="_blank"
       class="btn btn-link" title="Link zu Codexplo">Codexplo 2.0</a>
</div>

