<h1>A propos de swissbib Basel Bern</h1>
<p>swissbib Basel Bern recense un peu plus de 7 millions de titres des 200 <a href="<?= $this->basePath('Libraries') ?>" title="Liste der Institutionen">bibliothèques scientifiques de Bâle et de Berne</a> (Bibliothèques des universités de Bâle et de Berne, la bibliothèque nationale, quelques bibliothèques spécialisées, ainsi que les bibliothèques des universités de technologie.)</p>
<p>Le projet est soutenu par <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.informationsverbund.ch/21.0.html') ?>" target="_blank">le réseau IDS Basel Bern</a> et profite de l'infrastructure et du savoir-faire du catalogue national <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('https://www.swissbib.ch') ?>" target="_blank" title="swissbib">swissbib</a>.</p>
<h2>Que peut-on trouver dans swissbib Basel Bern?</h2>
<p>Dans swissbib Basel Bern une recherche peut être effectuée dans deux bases de données différentes:</p>
<p><strong>Livres et plus</strong></p>
<ul>
    <li>Les différents médias tels que les livres/les livres électroniques, les revues/les revues électroniques, les journaux, les CD/DVD, les bases de données etc.<strong> En régle générale les articles et les chapitres de ces médias</strong> ne sont pas mentionnés.</li>
    <li>Les revues scientifiques suisses numérisées (Projet retro.seals), avec un accès direct aux textes des articles.</li>
</ul>
<p><strong>Articles et plus</strong></p>
<ul>
    <li><strong> Les articles, les chapitres de livres, les contributions</strong> etc. des revues et livres électroniques et des bases de données qui sont mis à disposition par les universités de Bâle et de Berne. Dans la plupart des cas on peut avoir accès directement à la version électronique à partir d'un poste de l'université.</li>
    <li>Les ressources électroniques dont l'accès est gratuit et permettent ainsi d'être consultées en dehors des universités de Bâle et de Berne.</li>
</ul>
<p>Les titres qui ne possédent pas d'accès au texte intégral, peuvent être commandés via <i class="fa fa-external-link"></i> SFX-Services auprès de votre bibliothèque.</p>
<h2>Contact</h2>
<p>Nous vous aidons volontier pour vos recherches ainsi que pour les réservations dans notre catalogue et prenons en compte vos suggestions et critiques.</p>
<ul>
    <li>Pour les questions concernant votre compte usager ou bien certains documents, merci de bien vouloir vous adresser à la bibliothèque d'origine, c'est à dire à la <a href="<?= $this->basePath('Libraries') ?>" title="Liste der Institutionen">bibliothèque</a> d'où provient le document.</li>
    <li>Pour vos questions et suggestions concernant l'interface de recherche de swissbib Basel Bern: <a id="feedbackLink" class="modal-link" href="<?= $this->url('feedback-home') ?>"><?= $this->transEsc("menu.contact") ?></a></li>
</ul>
<h2>News</h2>
Abonnez vous à notre <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib-baselbern.blogspot.ch') ?>" target="_blank">Blog</a>.