<h1>Frais / Délais de livraison</h1>
<h2>Service du réseau de livraison IDS</h2>
<p>Les documents des bibliothèques participant au service du réseau de livraison IDS peuvent être récupérés et rapportés dans n'importe quelles autres bibliothèques du réseau:</p>
<ul>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken/a100/?S=1') ?>" target="_blank">Basel UB Hauptbibliothek</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken/a140/?S=1') ?>" target="_blank">Basel UB Medizin</a> (seulement livraison à Berne)</li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken/a125/?S=1') ?>" target="_blank">Basel UB Wirtschaft - SWA</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b404') ?>" target="_blank">Bern UB Zentralbibliothek</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b410') ?>" target="_blank">Bern UB Basisbibliothek Unitobler</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b500') ?>" target="_blank">Bern UB Bibliothek vonRoll</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b452') ?>" target="_blank">Bern UB Fachbereichsbibliothek Bühlplatz</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b465') ?>" target="_blank">Bern UB Juristische Bibliothek</a> (seulement récuperation)</li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b415') ?>" target="_blank">Bern UB Schweizerische Osteuropabibliothek</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zb.unibe.ch/aleph/biblinfo/b517.html') ?>" target="_blank">Bern PH Weiterbildung und Medienbildung</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zhbluzern.ch/index.php?id=1218') ?>" target="_blank">Luzern Zentral- und Hochschulbibliothek Sempacherstrasse</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zhbluzern.ch/index.php?id=1219') ?>" target="_blank">Luzern Zentral- und Hochschulbibliothek UNI/PH-Gebäude</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zhbluzern.ch/standorte/hochschule-luzern-wirtschaft/') ?>" target="_blank">Luzern Zentral- und Hochschulbibliothek Wirtschaft</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.unisg.ch/wissen/bibliothek') ?>" target="_blank">St. Gallen HSG</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.sg.ch/home/kultur/kantonsbibliothek.html') ?>" target="_blank">St. Gallen Kantonsbibliothek Vadiana</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zb.uzh.ch') ?>" target="_blank">Zürich Zentralbibliothek</a></li>
</ul>
<p><strong>Frais:</strong> Fr. 5.- par document. Paiement comptant à la réception du document. En cas de non-réception du document, le service vous sera facturé quand même.</p>
<p><strong>Délais de livraison:</strong> Les documents commandés en ligne sont réceptionnés par le service de livraison IDS tous les jours (sauf le samedi) et sont livrés dans la bibliothèque de votre choix dans un délai de 2 jours ouvrables. Les documents restent à votre disposition pendant une semaine.</p>
<h2>Les services de livraison de Bâle et Berne</h2>
<p>Les services de livraison internes de <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/ub-hauptbibliothek/dienstleistungen/ausleihe/kurier-und-fernleihe') ?>" target="_blank" title="Basler Kurier">Bâle</a> et <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/bestellen__ausleihen/kurier') ?>" target="_blank" title="Berner Kurier">Berne</a> sont gratuits.
<h2>Envois de documents des BU de Bâle et de Berne à domicile </h2>
<p><strong>Frais:</strong> Fr. 12.- par document. </p>
<p><strong>Délais de livraison:</strong> Les commandes sont traitées et envoyées du lundi au vendredi dans un délai de 24 heures. </p>
<h2>Envois de photocopies (par voie postale ou par mail) des BU de Bâle et de Berne </h2>
<p><strong>Frais pour clients privés:</strong> Fr. 8.- par tranche de 20 pages.</p>
<p><strong>Frais pour clients commerciaux:</strong> Fr. 24.- par commande jusqu’à 20 pages ; Fr. 8.- pour toute tranche supplémentaire de 20 pages
<p><strong>Délais de livraison:</strong> Traitement du lundi au vendredi dans un délai de 24 heures.</p>
<p>Les frais vous sont facturés par le réseau IDS Basel Bern.</p>
<p><strong>Contact:</strong> Inkasso-/Clearingstelle UB ZB Bern, +41 (0)31 631 92 21, <a href="mailto:clearing@ub.unibe.ch">clearing@ub.unibe.ch</a></p>
<h2>Envois de documents des autres bibliothèques du réseau à domicile</h2>
<p>Voir les conditions soumises par les autres bibliothèques sur leur site respectif: <a href="<?= $this->basePath('Libraries') ?>" title="Liste der Institutionen">Bibliothèque</a></p>