<h1>Recherche</h1>
<h2>Combiner des critères de recherche</h2>
<p>Les opérateurs booléens (AND, OR, NOT) permettent de relier de façon logique des critères de recherche les uns aux autres. Les opérateurs booléens sont écrits en majuscules.</p>
<table class="table table-striped">
    <tbody>
    <tr>
        <td><i>joyce ulysses</i></td>
        <td>Les deux critères apparaissent</td>
    </tr>
    <tr>
        <td><i>joyce AND ulysses</i></td>
        <td>Les deux critères apparaissent dans le même champ</td>
    </tr>
    <tr>
        <td><i>joyce OR ulysses</i></td>
        <td>Un des deux critères apparaît</td>
    </tr>
    <tr>
        <td><i>joyce NOT ulysses</i></td>
        <td><i>joyce</i> apparaît, mais pas <i>ulysses</i></td>
    </tr>
    <tr>
        <td>Combinaisons plus complexes</td>
        <td>Voir sous <a class="help-link" data-lightbox href="<?=$this->url('help-home')?>?topic=search" title="<?=$this->transEsc('Help with Search Operators')?>"><?=$this->transEsc("Help with Search Operators")?></a>.
        </td>
    </tr>
    </tbody>
</table>
<br />
<h2>Recherche de suite de mots avec guillemets</h2>
<table class="table table-striped">
    <tbody>
    <tr>
        <td><i>"street art"</i></td>
        <td>Les deux mots doivent se suivre.</td>
    </tr>
    <tr>
        <td><i>"street art"~5</i></td>
        <td>Les deux termes recherchés apparaissent en l’espace de cinq mots</td>
    </tr>
    <tr>
        <td><i>"PZB E 62 2:6"</i></td>
        <td>Cote</td>
    </tr>
    </tbody>
</table>
<br />
<h2>Troncatures</h2>
<table class="table table-striped">
    <tbody>
    <tr>
        <td rowspan="2">*</td>
        <td rowspan="2">remplace une suite de caractères de longueur variable</td>
        <td><i>cultur*</i></td>
        <td>culture, cultura, cultural, culturally etc.</td>
    </tr>
    <tr>
        <td><i>Fr*ib*urg</i></td>
        <td>Fribourg, Freiburg etc.</td>
    </tr>
    <tr>
        <td rowspan="2">?</td>
        <td rowspan="2">remplace 1 caractère ou un vide</td>
        <td><i>wom?n</i></td>
        <td>woman, women etc.</td>
    </tr>
    <tr>
        <td><i>Lind??ist</i></td>
        <td>Lindquist, Lindkvist, Lindqvist ecc.</td>
    </tr>
    <tr>
        <td>~</td>
        <td>si l'orthographe exacte n'est pas connue<br/></td>
        <td><i>Tschaikowski~</i></td>
        <td>Tschaikowski, Tchaïkovski, Čajkovskij etc.</td>
    </tr>
    </tbody>
</table>