<?
$headers = [
  'history_time'    => $this->transEsc('history_time'),
  'history_search'  => $this->transEsc('history_search'),
  'history_limits'  => $this->transEsc('history_limits'),
  'history_results' => $this->transEsc('history_results'),
  'action'          => $this->transEsc('history_' . ($this->showSaved ? 'delete' : 'save'))
];

$flippedContent = '';
?>
<table class="table table-striped hidden-xs hidden-sm">
  <thead>
    <tr>
        <th><?=$headers['history_time']?></th>
        <th><?=$headers['history_search']?></th>
        <th><?=$headers['history_limits']?></th>
        <th><?=$headers['history_results']?></th>
        <th class="hidden-print"><?=$headers['action']?></th>
    </tr>
  </thead>
  <tbody>
  <? foreach (($this->showSaved ? array_reverse($this->saved) : array_reverse($this->unsaved)) as $iteration => $info): ?>
    <tr class="<?=$iteration % 2 == 1 ? 'even' : 'odd'?>row">
      <td><?=$this->escapeHtml($this->dateTime()->convertToDisplayDateAndTime("U", $info->getStartTime()))?></td>
      <td>
          <a href="<?=$this->url($info->getOptions()->getSearchAction()) . $info->getUrlQuery()->getParams()?>">
            <?
          $desc = $info->getParams()->getDisplayQuery();
          echo empty($desc) ? $this->transEsc("history_empty_search") : $this->escapeHtml($desc);

            $flippedContent .= $this->render('search/history-table-flipped.phtml', array(
                'info'      => $info,
                'headers'   => $headers,
                'even'      => (0 === $iteration % 2),
                'showSaved' => $this->showSaved
            ));
        ?></a>
        <? if (method_exists($info,'getTarget')): ?>
           <br /><span class="meta"><?=$this->transEsc('tab.' . $info->getTarget())?></span>
        <? endif; ?>
      </td>
      <td>
        <?
        $info->getParams()->activateAllFacets();
        foreach ($info->getParams()->getFilterList() as $field => $filters):
          foreach ($filters as $i => $filter):
            if ($filter['operator'] == 'NOT') echo $this->transEsc('NOT') . ' ';
            if ($filter['operator'] == 'OR' && $i > 0) echo $this->transEsc('OR') . ' ';
            ?>
            <strong><?=$this->transEsc($field)?></strong>: <?=$this->escapeHtml($filter['displayText'])?><br/>
          <? endforeach;
        endforeach; ?>
      </td>
      <td><?=$this->localizedNumber($info->getResultTotal())?></td>
      <td class="hidden-print">
        <? if ($this->showSaved): ?>
          <a href="<?=$this->url('myresearch-savesearch')?>?delete=<?=urlencode($info->getSearchId())?>&amp;mode=history"><i class="fa fa-trash"></i> <?=$this->transEsc("history_delete_link")?></a>
        <? else: ?>
          <a href="<?=$this->url('myresearch-savesearch')?>?save=<?=urlencode($info->getSearchId())?>&amp;mode=history"><i class="fa fa-save"></i> <?=$this->transEsc("history_save_link")?></a>
        <? endif; ?>
      </td>
    </tr>
  <? endforeach; ?>
  </tbody>
</table>
<?=$flippedContent;?>