<h2>jusbib in tre mosse</h2>
<p>
    jusbib offre un accesso rapido, semplice e completo alla letteratura giuridica in Svizzera, sia in formato cartaceo che elettronico.
    jusbib permette di effettuare una ricerca simultanea nei cataloghi delle biblioteche universitarie e delle alte scuole
    svizzere, nonché della Biblioteca nazionale.
</p>

<p>
    Ecco come ricercare la documentazione in jusbib ed in seguito ottenere l’accesso ai documenti di cui avete bisogno.
</p>

<ol class="list">
    <li><a href="#search">Cercare</a></li>
    <li><a href="#refine">Trovare</a></li>
    <li><a href="#locate">Scegliere ed ordinare</a></li>
</ol>
<h2><a name="search"></a>Cercare</h2>
<div class="floatbox">
    <p>
        Inserite una o più parole nella maschera di ricerca.
    </p>
    <p>
        <em>Usando il segno asterisco <strong>*</strong> è possibile troncare o sostituire un <strong>numero qualsiasi</strong>
        di caratteri, ad esempio per la ricerca di parole con differenti terminazioni (oper* per 'Oper', 'Opern',
        'opéra', 'opéras', 'opera', 'opere' ecc.).</em>
    </p>
    <p>
        <em>Il punto di domanda <strong>?</strong> sostituisce <strong>un</strong> singolo carattere e permette di ricercare
        parole la cui ortografia varia (es. wom?n per 'woman' e per 'women').</em>
    </p>
    <p>
        <em>Inserendo i termini tra virgolette <strong>"..."</strong> è possibile ricercarli nell’ordine <strong>esatto dell’inserimento</strong>
        (es. "legal status").</em>
    </p>
</div>

<h2><a name="refine"></a>Trovare</h2>
<div class="floatbox">
    <h3>Filtri</h3>
    <p>
        E’ possibile delimitare la ricerca utilizzando i filtri sulla destra della lista dei risultati.
    </p>
    <p>
        Alla ricerca di un <strong>determinato autore</strong>? <br>La ricerca di un nome di persona darà come risultato
        una lista di documenti che lo hanno come autore, ma pure di documenti che ne trattano. Qualora si desideri ottenere
        unicamente gli scritti dell’autore cercato, è opportuno selezionare il suo nome nella lista del filtro <strong>Autore</strong>.
    </p>
    <p>
        Alla ricerca di un determinato <strong>soggetto</strong>? <br>Selezionate un termine che descrive l'argomento della
        ricerca utilizzando il filtro <strong>Soggetto</strong>.
    </p>
</div>

<h3>Ordinare i risultati</h3>
<p>
    L’ordinamento cronologico <strong>dal più recente al meno recente</strong> non vi mostra quanto cercato? Modificate l’ordine
    di apparizione dei risultati, ad esempio per &raquo;pertinenza&laquo;.
</p>

<h3>Dove potete ordinare i documenti trovati?</h3>
<p>
    Il simbolo <i class="fa fa-institution"></i> a destra di ciascun titolo permette di vedere quale biblioteca è in possesso
    di un esemplare. Cliccando sul nome della biblioteca si ottengono ulteriori informazioni.
</p>

<h2><a name="locate"></a>Scegliere ed ordinare</h2>
<div class="floatbox">
    <p>
        Cliccando sul titolo desiderato si ottiene la visualizzazione completa di tutti i dati bibliografici (titolo, autore,
        luogo di edizione, casa editrice, anno di pubblicazione, numero di pagine, edizione ecc.). Al di sotto della notizia
        bibliografica si trova l’elenco delle biblioteche che permettono l'accesso al documento. Cliccando sul simbolo del
        cuore  <i class="fa fa-heart"></i> è pure possibile definire alcune biblioteche come <strong>preferite</strong>, in modo che
        appaiano in cima alla lista per le successive ricerche.
    </p>
    <p>
        Cliccando sul <strong>nome della biblioteca</strong> si visualizzano localizzazione e segnatura del documento. Per molte biblioteche
        viene visualizzato anche lo stato del documento, vale a dire se è disponibile, già in prestito oppure riservato alla consultazione in loco.
    </p>

    <h3>Prestito / ordinazione</h3>
    <p>
        jusbib non consente di ordinare direttamente un documento. Per richiederlo o prenotarlo occorre utilizzare il link <strong>al catalogo</strong>
        ed identificarsi presso la biblioteca attraverso il catalogo locale.
    </p>
</div>

<h2>Identificazione</h2>
<h3>Perché identificarsi in jusbib?</h3>
<p>
    L’identificazione in jusbib permette di personalizzare diverse impostazioni. Potete:
</p>
<ul class="list">
    <li>riprendere le ricerche già effettuate</li>
    <li>definire le biblioteche preferite</li>
    <li>salvare le liste di risultati più a lungo</li>
    <li>configurare l’interfaccia di ricerca (lingua, lunghezza delle liste)</li>
</ul>
<p>
    Se non vi identificate, tutte le impostazioni vengono perse alla chiusura del browser.
</p>

<h2>Come funziona l’identificazione in jusbib?</h2>
<p>
    Quale servizio sovraregionale jusbib offre un’identificazione indipendente da qualsiasi biblioteca. Vi sono due possibilità:
</p>
<ul class="list">
    <li>
        <strong>switchAAI:</strong> Per gli studenti e per il personale di università, alte scuole ed altre istituzioni viene utilizzato
        il servizio nazionale di switch. L’identificazione viene messa a disposizione dalle istituzioni stesse ed è altresì utilizzata
        dagli studenti per altri servizi quali VPN o piattaforme di apprendimento
        (<a href="https://www.switch.ch/it/services/aai/" target="_blank" title="Info switchAAI">Ulteriori informazioni</a>).
    </li>
    <li>
        <strong>switch Guest Login:</strong> E’ l’accesso per coloro che non possono identificarsi via switchAAI poiché non
        appartenenti ad alcun ateneo. Anche questo tipo d’identificazione viene messo a disposizione da switch
        (<a href="https://www.switch.ch/aai/support/tools/guest-login/" target="_blank" title="Info Guest Login">Ulteriori informazioni</a>).
    </li>
</ul>

<h2>Perché bisogna effettuare il logoff?</h2>
<p>
    Se lavorate su computer pubblici o condivisi, al termine della sessione è opportuno effettuare il logoff e <strong>chiudere il
    browser</strong> onde evitare che altri possano utilizzare il vostro conto.
</p>
