<?php
/** @var Array[] $items */
/** @var Array[] $filters */
/** @var Integer $page */
/** @var Integer $total */
/** @var Integer $year */
/** @var Integer $volume */
/** @var Array $baseUrlParams */
/** @var String $institution */

$baseUrl = $this->url('holdings-holding-items', $baseUrlParams) . '?';

$institutionLabel = $this->zendTranslate($institution, 'institution');

?>
    <form id="holdings-items-filter-form" action="<?= $this->escapeHtml($baseUrl) ?>">
      <div class="row">
        <div class="col-lg-6">
        <?php if (sizeof($filters['years'])): ?>
            <label for="holding-items-filter-year"><?= $this->transEsc('Show year') . ':' ?></label>
            <select id="holding-items-filter-year" class="form-control" name="year" onchange="var year=document.getElementById('holding-items-filter-year').value; swissbib.Holdings.openHoldingItemsPopup('<?= $baseUrl . "&year=" ?>'+year, '-')">
              <option value=""><?= $this->transEsc('All years') ?></option>
              <?php foreach ($filters['years'] as $yearValue): ?>
                <option <?= ($yearValue == $year ? 'selected="selected"' : '') ?>><?= $yearValue ?></option>
              <?php endforeach; ?>
            </select>
          <?php endif; ?>
        </div>

        <div class="col-lg-6">
          <?php if (sizeof($filters['volumes'])): ?>
            <label for="holding-items-filter-volume"><?= $this->transEsc('Show volumes') . ':' ?></label>
            <select id="holding-items-filter-volume" class="form-control" name="volume" onchange="var volume=document.getElementById('holding-items-filter-volume').value; swissbib.Holdings.openHoldingItemsPopup('<?= $baseUrl . "&volume=" ?>'+volume, '-')">
              <option value=""><?= $this->transEsc('All volumes') ?></option>
              <?php foreach ($filters['volumes'] as $volumeValue): ?>
                <option <?= ($volumeValue == $volume ? 'selected="selected"' : '') ?>><?= $volumeValue ?></option>
              <?php endforeach; ?>
            </select>
          <?php endif; ?>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-6">

        </div>
        <div class="col-lg-6 pull-right">
          <?= $this->holdingItemsPaging($baseUrl, $total, $page, $year, $volume) ?>
        </div>
      </div>
    </form>
<div class="row">
  <div class="col-lg-12">
    <h4><?= $this->escapeHtml($institutionLabel) ?></h4>
  </div>
</div>
<?php if (sizeof($items)): ?>
  <div class="row">
    <div class="col-lg-12">
      <?= $this->render('Holdings/items') ?>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6">

    </div>
    <div class="col-lg-6">
      <?= $this->holdingItemsPaging($baseUrl, $total, $page, $year, $volume) ?>
    </div>
  </div>

<?php else: ?>
  <div class="row">
    <div class="col-lg-12">
      <p><?= $this->transEsc('No Holdings for filters') ?></p>
    </div>
  </div>
<?php endif; ?>
