<?php
/** @var Array[] $holdings */
/** @var String $record */
/** @var String $institution */
/** @var String $recordTitle */

$idTable = 'holdings-holding-' . $record . '-' . $institution;
$flippedContent = '';

$headers = [
  'actions' => '&nbsp;',
  'availability' => $this->transEsc('Availability'),
  'location' => $this->transEsc('Location'),
  'callnr' => $this->transEsc('Call Number'),
  'description' => $this->transEsc('Description')
];

?>
<table class="table table-striped holdings-holding holdingTable hidden-xs hidden-sm" id="<?= $this->escapeHtml($idTable) ?>">
    <thead>
    <tr>
        <th class="actions">&nbsp;</th>
        <th class="availability"><?= $this->transEsc('Availability') ?></th>
        <th class="location"><?= $this->transEsc('Location') ?></th>
        <th class="callnr"><?= $this->transEsc('Call Number') ?></th>
        <th class="description"><?= $this->transEsc('Description') ?></th>
    </tr>
    </thead>
    <tbody>
    <?php
    if (!empty($holdings)) {
        foreach ($holdings as $hkey => $holding) {
            echo $this->render(
                'Holdings/holding-holding.phtml',
                array(
                    'holding'     => $holding,
                    'record'      => $record,
                    'recordTitle' => $recordTitle,
                    'headers'     => $headers
                )
            );
            $flippedContent .= $this->render(
                'Holdings/holding-holding-flipped.phtml',
                array(
                    'holding'     => $holding,
                    'record'      => $record,
                    'recordTitle' => $recordTitle,
                    'even'        => (0 === $hkey % 2)
                )
            );
        }
    }
    if (!empty($items)) {
        foreach ($items as $ikey => $item) {
            echo $this->render(
                'Holdings/holding-item.phtml',
                array(
                    'item'        => $item,
                    'record'      => $record,
                    'recordTitle' => $recordTitle
                )
            );

            $flippedContent .= $this->render(
                'Holdings/holding-item-flipped.phtml',
                array(
                    'item'        => $item,
                    'record'      => $record,
                    'recordTitle' => $recordTitle,
                    'headers'     => $headers,
                    'even'        => (0 === $ikey % 2)
                )
            );
        }
    }
    ?>
    </tbody>
</table>
<?= $flippedContent; ?>