<?php
/** @var Integer $pages */
/** @var Integer $active */
/** @var String $url */
/** @var Integer $startPage */
/** @var Integer $endPage */

$fullUrl = $baseUrl;

if ($year) {
  $fullUrl .= '&year=' . urlencode($year);
}
if ($volume) {
  $fullUrl .= '&volume=' . urlencode($volume);
}

$previous = $active > 1 ? true : false;
$next = $active < $pages ? true : false;

?>
<div class="pagination-container pagination-container-holding-items hidden-print" id="holding-items-popup-paging">
  <?php if ($pages > 1): ?>

    <ul class="pagination">
      <li class="hidden-sm hidden-xs page">
        <a href="#"><?= $this->transEsc('pagination.page') ?>:</a>
      </li>

      <? if ($previous): ?>
        <li>
          <a href="<?= "javascript:swissbib.Holdings.openHoldingItemsPopup('" . $fullUrl . "&page=" . ($active - 1) . "', '-')" ?>"
             title="<?= $this->transEsc('Prev') ?>">
            <i class="fa fa-caret-left"></i>
          </a>
        </li>
      <? else: ?>
        <li class="inactive">
          <a>
            <i class="fa fa-caret-left"></i>
          </a>
        </li>
      <? endif; ?>

      <li class="page-numbers">
        <a>
          <span class="<?= $previous ? 'standard' : 'marked' ?>">
            <?= $this->localizedNumber($active) ?>
          </span>
          <?= $this->transEsc('of') ?>
          <span class="<?= $next ? 'standard' : 'marked' ?>">
            <?= $this->localizedNumber($pages) ?>
          </span>
        </a>
      </li>

      <? if ($next): ?>
        <li>
          <a href="<?= "javascript:swissbib.Holdings.openHoldingItemsPopup('" . $fullUrl . "&page=" . ($active + 1) . "', '-')" ?>"
             title="<?= $this->transEsc('Next'); ?>">
            <i class="fa fa-caret-right"></i>
          </a>
        </li>
      <? else: ?>
        <li class="inactive">
          <a>
            <i class="fa fa-caret-right"></i>
          </a>
        </li>
      <? endif; ?>
    </ul>

  <?php endif; ?>

</div>
