<?php
/** @var Array[] $items */
/** @var String $record */
/** @var String $recordTitle */

$headers = [
  'actions'      => '&nbsp;',
  'availability' => $this->transEsc('Availability'),
  'location'     => $this->transEsc('Location'),
  'callnr'       => $this->transEsc('Call Number'),
  'description'  => $this->transEsc('Description')
];

// Items
foreach ($items as $ikey => $item) {
  echo $this->render('Holdings/holding-item-flipped.phtml', array(
      'item'               => $item,
      'record'             => $record,
      'recordTitle'        => $recordTitle,
      'headers'            => $headers,
      'even'               => (0 === $ikey % 2),
      'showInAllViewPorts' => true
  ));
}
?>