<div class="home-content-box">
    <h2 class="lead">Verzögerte Aktualisierung der Daten</h2>
    <p>Der Datenbestand des Bibliothekssystems Basel/Bern wurde in den letzten Tagen nahezu komplett aktualisiert. Wegen dieser Massenupdates stimmt die Anzeige in swissbib Basel Bern derzeit nicht in allen Fällen mit dem klassischen Katalog überein. Für die Abfrage des aktuellen Datenbestands bitten wir Sie, bis zum 12. Oktober den klassischen Katalog zu benutzen.</p>

    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://aleph.unibas.ch/F') ?>" target="_blank" class="btn btn-link">Klassischer Katalog</a>

</div>
