<div class="home-content-box">
  <h2 class="lead">Mahnungen Universität Bern</h2>
  <p>Wir möchten Sie darauf hinweisen, dass Mahnungen der Universitätsbibliothek Bern bei verschiedenen Mailprovidern als Spam gefiltert werden: </p>
  <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.unibe.ch/universitaet/dienstleistungen/universitaetsbibliothek/service/ausleihe/index_ger.html') ?>" target="_blank" class="btn btn-link">weitere Informationen zu Spam Mail</a>


</div>
