<div class="home-content-box">
  <h2 class="lead">Maintenance Work until Sunday, 11.9.2016</h2>
  <img class="img-responsive" src="<?= $this->basePath('themes/sbvfrdmulti/images/underconstruction.jpg') ?>" width="230">
  <br/>
  <p>Because of maintenance work item availability information currently can't be displayed and the following functionalities aren't available: "Delete reservations" and "Bookings". We apologize for any inconveniences.</p>
</div>