<div class="home-content-box">
    <h2 class="lead">Ihr Benutzungskonto - das unverzichtbare Tool</h2>
    <p>Im Benutzungskonto können Sie Ihre Adresse ändern, Ausleihen verlängern, Merklisten anlegen, Suchhistorien und Ihre Favoritenbibliothek abspeichern und vieles mehr:</p>

    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib-baselbern.blogspot.ch/search/label/Tipp') ?>" target="_blank" class="btn btn-link">Mehr Informationen</a>

</div>
