<div class="home-content-box">
    <h2 class="lead">Signaturen und ihre Bedeutung</h2>
    <p>Lesen Sie hier, wie Sie bereits auf den ersten Blick wichtige Informationen aus der Signatur eines Buches ablesen können.</p>
    
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib-baselbern.blogspot.ch/search/label/Tipp') ?>" target="_blank" class="btn btn-link">Mehr Informationen im Blog</a>

</div>
