<?php

/** @var  Swissbib\RecordDriver\SolrMarc $record */
$record = $this->driver;
$holdings = $record->getHoldingsStructure();

// Copy favorites to own container
$holdings = $this->extractFavoriteInstitutionsForHoldings($holdings);

// Set page title.
$this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());

?>
<? if ($holdings): ?>

  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <? foreach ($holdings as $groupCode => $group): ?>
    <!-- begin: group <?= $groupCode ?> -->
    <div class="panel panel-default" id="holdings-<?= $groupCode ?>">
      <!-- begin: group heading -->
      <div class="panel-heading" role="tab" id="heading-<?= $groupCode ?>">
        <h3 class="panel-title">
          <a data-toggle="collapse" href="#collapse-<?= $groupCode ?>" aria-expanded="false" aria-controls="collapse-<?= $groupCode ?>">
            <? if (is_array($group['label'])): ?>
              <? $group['label'] = implode('', array_unique($group['label'])); ?>
            <? endif; ?>
            <? if ($group['label'] == 'mylibraries'): ?>
              <span><?= $this->zendTranslate($group['label']) ?></span>
            <? else: ?>
              <span><?= $this->zendTranslate($group['label'], 'group') ?></span>
            <? endif; ?>
          </a>
        </h3>
      </div>
      <!-- end: group heading -->
      <!-- begin: group content -->
      <div id="collapse-<?= $groupCode ?>" level="1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-<?= $groupCode ?>">
        <div class="list-group">

          <div class="panel-group" id="institutions-<?= $groupCode ?>" role="tablist" aria-multiselectable="true">
          <? foreach ($group['institutions'] as $institutionCode => $institution): ?>

            <!-- begin: institution <?= $institutionCode ?>-->
            <div class="panel panel-default institutionBox institution-<?= $institutionCode ?>-box" id="holding-institution-<?= $groupCode ?>-<?= $institutionCode ?>-box">
              <!-- begin: institution heading -->
              <div class="panel-heading" role="tab" id="heading-<?= $groupCode ?>-<?= $institutionCode ?>">
                <h4 class="panel-title clearfix">
                  <div class="miniactions miniactions-<?= $institutionCode ?> pull-right">
                    <div class="institutionFavorite">
                      <a href="javascript:void(0)" title="<? if (isset($institution['favorite']) && $institution['favorite']): ?> <?= $this->transEsc('mylibraries.remove')?> <? else: ?> <?= $this->transEsc('mylibraries.add')?> <? endif; ?>"></a>
                    </div>
                  </div>
                  <a data-toggle="collapse" href="#collapse-<?= $groupCode ?>-<?= $institutionCode ?>" aria-expanded="false" aria-controls="collapse-<?= $groupCode ?>-<?= $institutionCode ?>"
                     id="holding-institution-<?= $groupCode ?>-<?= $institutionCode ?>" class="toggler institutionToggler">
                    <?= $this->escapeHtml($this->zendTranslate($institution['label'], 'institution')) ?>
                  </a>
                </h4>
              </div>
              <!-- end: institution heading -->

              <!-- begin: institution content -->
              <div id="collapse-<?= $groupCode ?>-<?= $institutionCode ?>" level="2" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-<?= $groupCode ?>-<?= $institutionCode ?>">
                <div class="panel-body">
                  <!--begin: holdings-table -->
                  <div class="holding-institution-<?= $groupCode ?>-<?= $institutionCode ?>" id="holding-institution-<?= $institutionCode ?>">
                    <div class="holdingsAjaxSpinner holding-ajax-spinner-<?= $groupCode ?>-<?= $institutionCode ?>">
                      <i class="fa fa-spinner fa-spin"></i>
                      <span>Loading...</span>
                    </div>
                  </div>
                  <!--end: holdings-table -->
                </div>
              </div>
              <!-- end: institution content -->
            </div>
            <!-- end: institution <?= $institutionCode ?> -->

          <? endforeach; ?>
          </div>

        </div>
      </div>
      <!-- end: group content -->
    </div>
    <!-- end: group <?= $groupCode ?> -->

    <? endforeach; ?>

  </div>

  <div id="holdings-items-popup" style="display:none">
    Loading...
  </div>

  <script type="text/javascript">
    swissbib.Holdings.initRecord('<?=$record->getUniqueID()?>');
    swissbib.HoldingFavorites.initRecord('<?=$record->getUniqueID()?>');
    swissbib.Accordion.initRecord('<?=$record->getUniqueID()?>');
    vufindString.favoriteReload = '<?=$this->transEsc('mylibraries.reload')?>';
  </script>

<? else: ?>

  <?= $this->render('RecordTab/holdingils-noholdings') ?>

<? endif; ?>