# seachspecs.yaml for swissbib
# see extensive documentation in head of file /config/vufind/searchspecs.yaml
# ###########################################################################

# These searches use Dismax when possible:

AllFields:
  DismaxHandler: edismax
  DismaxFields:
    - title_short^1000            # main title, i.e. 245 $a
    - title_alt^200
    - title_sub^200
    - title_old^200
    - title_new^200
    - author^750                          # all entries main name forms
    - author_additional^100               # all entries additional fields
    - author_additional_dsv11_txt_mv^100  # variants from dsv11
    - title_additional_dsv11_txt_mv^100
    - series^200
    - topic^500                   # all verbal topics, i.e. 6xx
    - addfields_txt_mv^50         # additional fields
    - publplace_txt_mv^25         # publication country and place, i.e. 752ad
    - publplace_dsv11_txt_mv^25
    - fulltext                    # imported fulltext, i.e. TOC/Abstracts
    - callnumber^1000             # callnumbers (works only when quoted) with high boost
    - ctrlnum^1000
    - publishDate
    - isbn
    - variant_isbn_isn_mv
    - issn
    - localcode                     # local codes (field 909)
    - id
  DismaxParams:
    - [pf, 'title_short^1000']
    - [ps, '2']
    - [bf, 'recip(abs(ms(NOW/DAY,freshness)),3.16e-10,100,100)']
#  DismaxParams:
#  boost param as in old solrconfig.xml
  QueryFields:
    0:
      0:
        - OR
        - 50
      title_short:
        - [onephrase, 1000]
      title_alt:
        - [onephrase, 600]
        - [and, 500]
      title_additional_dsv11_txt_mv:
        - [onephrase, 600]
        - [and, 500]
      title_sub:
        - [onephrase, 400]
      title_old:
        - [onephrase, 300]
        - [and, 250]
      title_new:
        - [and, 200]
      title:
        - [onephrase, 100]
    author:
      - [and, 750]
    author_additional:
      - [and, 100]
    author_additional_dsv11_txt_mv:
      - [and, 100]
    series:
      - [and, 50]
    topic:
      - [onephrase, 300]
      - [and, 250]
    addfields_txt_mv:
      - [onephrase, 150]
      - [and, 125]
    publplace_txt_mv:
      - [onephrase, 150]
      - [and, 125]
    publplace_dsv11_txt_mv:
      - [onephrase, 150]
      - [and, 125]
    fulltext:
      - [or, ~]
    localcode:
      - [and, ~]
  #FilterQuery: "union:SNL OR institution:B424 OR (union:NEBIS NOT origcountry_isn_mv:sz AND (subtop_gnd:Tunnelbau OR subgeo_gnd:(Gotthard-Basistunnel OR Gotthardgruppe) OR sublocal:Tunnelbau)) OR (union:RERO NOT origcountry_isn_mv:sz AND subgeo_rero:Saint-Gothard) OR (union:SBT NOT origcountry_isn_mv:sz AND subgeo_sbt:\"San Gottardo\")"
  #FilterQuery: "union:SNL OR institution:B424"
  #FilterQuery: "union:SNL OR institution:B424 OR (NOT origcountry_isn_mv:sz AND (union:NEBIS OR union:RERO OR union:SBT) AND (topic:Tunnelbau OR topic:Gotthard OR topic:Saint-Gothard OR topic:\"San Gottardo\"))"
  #FilterQuery: "union:SNL OR institution:B424 OR (NOT origcountry_isn_mv:sz AND (union:NEBIS OR union:RERO OR union:SBT) AND topic:Tunnelbau)"
  FilterQuery: "topic:Tunnelbau OR topic:Gotthard OR topic:\"Saint-Gothard\" OR topic:\"San Gottardo\" NOT (union:SNL OR institution:B424)"

Author:
  DismaxHandler: edismax
  DismaxFields:
    - author^100
    - author_additional^20
    - author_additional_dsv11_txt_mv^20
  QueryFields:
    author:
      - [onephrase, 350]
      - [and, 200]
      - [or, 100]
    author_additional:
      - [onephrase, 50]
      - [and, 50]
      - [or, 20]
    author_additional_dsv11_txt_mv:
      - [onephrase, 50]
      - [and, 50]
      - [or, 20]
    FilterQuery: "topic:Tunnelbau OR topic:Gotthard OR topic:\"Saint-Gothard\" OR topic:\"San Gottardo\" NOT (union:SNL OR institution:B424)"

ISN:
  DismaxFields:
    - isbn
    - variant_isbn_isn_mv
    - issn
    - ismn_isn_mv
    - doi_isn_mv
    - urn_isn_mv
  QueryFields:
    issn:
      - [and, 100]
      - [or, ~]
    isbn:
      - [and, 100]
      - [or, ~]
    isbn_variation:
      - [and, 100]
      - [or, ~]
    ismn_isn_mv:
      - [and, 100]
      - [or, ~]
    doi_isn_mv:
      - [and, 100]
      - [or, ~]
    urn_isn_mv:
      - [and, 100]
      - [or, ~]
  FilterQuery: "topic:Tunnelbau OR topic:Gotthard OR topic:\"Saint-Gothard\" OR topic:\"San Gottardo\" NOT (union:SNL OR institution:B424)"

Subject:
  DismaxHandler: edismax
  DismaxFields:
    - topic^150
  QueryFields:
    topic:
      - [onephrase, 350]
  DismaxParams:
    - [bf, 'recip(abs(ms(NOW/DAY,freshness)),3.16e-10,100,100)']

JournalTitle:
  DismaxFields:
    - title_short^1000
    - title_alt^200
    - title_sub^200
    - title_old^200
    - title_new^200
  QueryFields:
    title_short:
      - [onephrase, 10000]
    title_sub:
      - [onephrase, 200]
    title_alt:
      - [onephrase, 200]
    title_old:
      - [onephrase, 200]
    title_new:
      - [onephrase, 200]
  FilterQuery: "format_str_mv:(CR0305* OR CR0306* OR CR0307*) AND topic:Tunnelbau OR topic:Gotthard OR topic:\"Saint-Gothard\" OR topic:\"San Gottardo\" NOT (union:SNL OR institution:B424)"
  DismaxParams:
    - [pf, 'title_short^100000']
    - [ps, '2']


FRBR:
  QueryFields:
    groupid_isn_mv:
      - [onephrase, 500]

WLC:
  DismaxFields:
    - localcode_isn_mv
  QueryFields:
    localcode_isn_mv:
      - [onephrase, ~]
  FilterQuery: "topic:Tunnelbau OR topic:Gotthard OR topic:\"Saint-Gothard\" OR topic:\"San Gottardo\" NOT (union:SNL OR institution:B424)"

WNEL:
  DismaxFields:
    - itemnote_isn_mv
  QueryFields:
     itemnote_isn_mv:
        - [or, ~]

WFC:
  DismaxFields:
    - classif_912
  QueryFields:
    classif_912:
      - [onephrase, ~]

FormerOwner:
  DismaxFields:
    - author_fmo_txt_mv
  QueryFields:
    author_fmo_txt_mv:
      - [and, ~]

Annotator:
  DismaxFields:
    - author_ann_txt_mv
  QueryFields:
    author_ann_txt_mv:
      - [and, ~]

RaraPerson:
  DismaxFields:
    - author_fmo_txt_mv
    - author_ann_txt_mv
  QueryFields:
    author_ann_txt_mv:
      - [and, ~]
    author_fmo_txt_mv:
      - [and, ~]

Title:
  DismaxHandler: edismax
  DismaxFields:
    - title_short^1000            # main title, i.e. 245 $a
    - title_alt^200
    - title_additional_dsv11_txt_mv^200
    - title_sub^200
    - title_old^200
    - title_new^200
    - series^100
    - series2
    - series^200
  QueryFields:
    title_short:
      - [onephrase, 500]
    title_alt:
      - [onephrase, 450]
      - [and, 400]
    title_additional_dsv11_txt_mv:
      - [onephrase, 450]
      - [and, 400]
    title_sub:
      - [onephrase, 400]
    title_old:
      - [onephrase, 300]
      - [and, 250]
    title_alt:
      - [and, 200]
    title_new:
      - [and, 100]
    series:
      - [onephrase, 100]
      - [and, 50]
    DismaxParams:
    - [bf, 'recip(abs(ms(NOW/DAY,freshness)),3.16e-10,100,100)']
  FilterQuery: "topic:Tunnelbau OR topic:Gotthard OR topic:\"Saint-Gothard\" OR topic:\"San Gottardo\" NOT (union:SNL OR institution:B424)"

Series:
  DismaxHandler: edismax
  DismaxFields:
    - series^100
  QueryFields:
    series:
      - [onephrase, 500]
      - [and, 200]
      - [or, 100]
    DismaxParams:
    - [bf, 'recip(abs(ms(NOW/DAY,freshness)),3.16e-10,100,100)']
  FilterQuery: "topic:Tunnelbau OR topic:Gotthard OR topic:\"Saint-Gothard\" OR topic:\"San Gottardo\" NOT (union:SNL OR institution:B424)"

# These are advanced searches that never use Dismax:
id:
  QueryFields:
    id:
      - [onephrase, ~]
  FilterQuery: "topic:Tunnelbau OR topic:Gotthard OR topic:\"Saint-Gothard\" OR topic:\"San Gottardo\" NOT (union:SNL OR institution:B424)"

# Fields for exact matches originating from alphabetic browse
ids:
  QueryFields:
    id:
      - [or, ~]
  FilterQuery: "topic:Tunnelbau OR topic:Gotthard OR topic:\"Saint-Gothard\" OR topic:\"San Gottardo\" NOT (union:SNL OR institution:B424)"

CallNumber:
  # We use two similar munges here -- one for exact matches, which will get
  # a very high boost factor, and one for left-anchored wildcard searches,
  # which will return a larger number of hits at a lower boost.
  # adapted for swissbib usage
  CustomMunge:
    callnumber_exact:
      # Strip whitespace and quotes:
      - [preg_replace, '/[ "]/', ""]
      # Escape colons (unescape first to avoid double-escapes):
      - [preg_replace, "/(\\\:)/", ':']
      - [preg_replace, '/:/', '\:']
      # Strip pre-existing trailing asterisks:
      - [preg_replace, "/\*+$/", ""]
    callnumber_fuzzy:
      # Strip whitespace and quotes:
      - [preg_replace, '/[ "]/', ""]
      # Escape colons (unescape first to avoid double-escapes):
      - [preg_replace, "/(\\\:)/", ':']
      - [preg_replace, '/:/', '\:']
      # Strip pre-existing trailing asterisks, then add a new one:
      - [preg_replace, "/\*+$/", ""]
      - [append, "*"]
  QueryFields:
    callnumber:
      - [callnumber_exact, 1000]
      - [callnumber_fuzzy, ~]
  FilterQuery: "topic:Tunnelbau OR topic:Gotthard OR topic:\"Saint-Gothard\" OR topic:\"San Gottardo\" NOT (union:SNL OR institution:B424)"

year:
  DismaxFields:
    - publishDate^100
  QueryFields:
    publishDate:
      - [and, 100]
      - [or, ~]
  FilterQuery: "topic:Tunnelbau OR topic:Gotthard OR topic:\"Saint-Gothard\" OR topic:\"San Gottardo\" NOT (union:SNL OR institution:B424)"

language:
  QueryFields:
    language:
      - [and, ~]
  FilterQuery: "topic:Tunnelbau OR topic:Gotthard OR topic:\"Saint-Gothard\" OR topic:\"San Gottardo\" NOT (union:SNL OR institution:B424)"

oclc_num:
  CustomMunge:
    oclc_num:
      - [preg_replace, "/[^0-9]/", ""]
      # trim leading zeroes:
      - [preg_replace, "/^0*/", ""]
  QueryFields:
    oclc_num:
      - [oclc_num, ~]
  FilterQuery: "topic:Tunnelbau OR topic:Gotthard OR topic:\"Saint-Gothard\" OR topic:\"San Gottardo\" NOT (union:SNL OR institution:B424)"

ctrlnum:
  CustomMunge:
    ctrlnum:
      - [preg_replace, "/[\(\)]/", ""]
  QueryFields:
    ctrlnum:
      - [ctrlnum, ~]
  FilterQuery: "topic:Tunnelbau OR topic:Gotthard OR topic:\"Saint-Gothard\" OR topic:\"San Gottardo\" NOT (union:SNL OR institution:B424)"

Autosuggest:
  DismaxHandler: dismax
  DismaxFields:
    - title_short
    - author
    - author_additional
  QueryFields:
    title_short:
      - [onephrase, 350]
      - [and, 200]
      - [or, 100]
    author:
      - [onephrase, 350]
      - [and, 200]
      - [or, 100]
    author_additional:
      - [onephrase, 50]
      - [and, 50]
      - [or, 20]

