<h1>Ricerca</h1>

<h2>Combinare più termini</h2>
<p>Gli operatori booleani (AND, OR e NOT) permettono di combinare in maniera logica diversi termini di ricerca. Gli operatori devono essere scritti in caratteri maiuscoli.</p>
<table class="table table-striped">
    <tbody>
    <tr>
        <td><i>joyce ulysses</i></td>
        <td>Entrambi i termini sono presenti nella notizia bibliografica</td>
    </tr>
    <tr>
        <td><i>joyce AND ulysses</i></td>
        <td>Entrambi i termini sono presenti nel medesimo campo descrittivo</td>
    </tr>
    <tr>
        <td><i>joyce OR ulysses</i></td>
        <td>Uno dei due termini è presente nella notizia bibliografica</td>
    </tr>
    <tr>
        <td><i>joyce NOT ulysses</i></td>
        <td>Nella notizia bibliografica è presente <i>joyce</i>, ma non <i>ulysses</i></td>
    </tr>
    <tr>
        <td>Ricerche più complesse</td>
        <td>Vedi <a class="help-link" data-lightbox href="<?=$this->url('help-home')?>?topic=search" title="<?=$this->transEsc('Help with Search Operators')?>"><?=$this->transEsc("Help with Search Operators")?></a>.
        </td>
    </tr>
    </tbody>
</table>
<br />
<h2>Ricerca per frase o locuzione tramite virgolette</h2>
<table class="table table-striped">
    <tbody>
    <tr>
        <td><i>"street art"</i></td>
        <td>I termini devono apparire nello stesso identico ordine.</td>
    </tr>
    <tr>
        <td><i>"street art"~5</i></td>
        <td>I due termini devono essere presenti entro un intervallo massimo di 5 parole.</td>
    </tr>
    <tr>
        <td><i>"PZB E 62 2:6"</i></td>
        <td>Segnatura</td>
    </tr>
    </tbody>
</table>
<br />
<h2>Segni di troncamento</h2>
<table class="table table-striped">
    <tbody>
    <tr>
        <td rowspan="2">*</td>
        <td rowspan="2">sostituisce un numero qualsiasi di caratteri</td>
        <td><i>cultur*</i></td>
        <td>culture, cultura, cultural, culturally, ecc.</td>
    </tr>
    <tr>
        <td><i>Fr*ib*urg</i></td>
        <td>Fribourg, Freiburg, ecc.</td>
    </tr>
    <tr>
        <td rowspan="2">?</td>
        <td rowspan="2">sostituisce un singolo carattere</td>
        <td><i>wom?n</i></td>
        <td>woman, women, ecc.</td>
    </tr>
    <tr>
        <td><i>Lind??ist</i></td>
        <td>Lindquist, Lindkvist, Lindqvist, ecc.</td>
    </tr>
    <tr>
        <td>~</td>
        <td>ricerca approssimativa <br/>(ortografia esatta non nota)</td>
        <td><i>Tschaikowski~</i></td>
        <td>Tschaikowski, Tchaïkovski, Čajkovskij, ecc.</td>
    </tr>
    </tbody>
</table>