<div class="home-content-box">
    <h2 class="lead">Linked Swissbib</h2>
    <p>
        Das Projekt linked.swissbib.ch hat das Ziel, den Metakatalog swissbib mit einem neuen Service verlinkter Daten in das semantische Web zu integrieren. Dies bedeutet, dass die Metadaten von Swissbib in ein semantisches Format – nach dem RDF-Modell (Resource Description Framework) – umgewandelt werden müssen. Die Publikation von Daten wird in 2017 geschehen. Erfahren Sie mehr dazu mit vier Blog-Artikel über das ganze Prozess.
    </p>
    <a href="http://swissbib.blogspot.ch/2016/04/swissbib-data-goes-linked-teil-1.html"
       target="_blank" class="btn btn-link" title="Link zum Blog">Mehr Informationen</a>
</div>