<div class="home-content-box">
    <h2 class="lead">Neuigkeiten</h2>
    <p>
        Als nationaler Katalog weist swissbib die Bestände von gut 20 Verbünden, Repositories und digitalen Bibliotheken nach.
        Ab dem 10. Juni 2015 ist auch
        <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://boris.unibe.ch/') ?>" target="_blank" title="BORIS">BORIS</a>
        (Bern Open Repository and Information System) mit gegen 5000 frei zugänglichen Dokumenten dabei.
    </p>
    <a href="<?= $this->basePath('Search/Results?filter[]=union:&quot;BORIS&quot;') ?>" class="btn btn-link">BORIS-Dokumente</a>
</div>

