<div class="home-content-box">
    <h2 class="lead">Bibliotheksverbund Alexandria</h2>
    <p>
        Nach dem Umstieg auf ein neues Bibliothekssystem konnten die Daten des Verbunds Alexandria nicht mehr
        aktualisiert werden. Seit November 2015 ist dies behoben: Die Bestände von 20 Bibliotheken inner- und ausserhalb
        der Bundesverwaltung werden in swissbib wieder tagesaktuell nachgewiesen.
    </p>
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib.blogspot.com/2015/12/alexandria-wieder-tagesaktuell-in-swissbib.html') ?>"
       target="_blank" class="btn btn-link" title="Link zum Blog">Mehr Informationen</a>
</div>