<div class="home-content-box">
    <h2 class="lead">Linked Swissbib</h2>
    <p>The project linked.swissbib.ch aims to integrate the metacatalog swissbib into the semantic web, with the creation of a Linked Data
    service. This implies the transformation of the metadata of swissbib into a semantic format based on the RDF model (Resource Description
    Framework). The publication of the data will happen in 2017. Learn more about the details with 4 blog tickets (in German or French).
    </p>
    <a href="http://swissbib.blogspot.ch/2016/04/swissbib-data-goes-linked-teil-1.html"
       target="_blank" class="btn btn-link" title="Link to blog post">Additional information</a>
</div>