<div class="home-content-box">
    <h2 class="lead">Library network Alexandria</h2>
    <p>
        After the switch to a new library management system, the data of the network Alexandria could not be updated.
        After November 2015 this has been rectified: The collections of 20 libraries within and outside of the federal
        administration are being refreshed on a daily basis.
    </p>
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib.blogspot.com/2015/12/alexandria-wieder-tagesaktuell-in-swissbib.html') ?>"
       target="_blank" class="btn btn-link" title="Link to our blog">Additional information</a>
</div>