<div class="home-content-box">
    <h2 class="lead">National licences</h2>
    <p>In 2015, Switzerland launched a Swiss National Licences project for online contents, under the lead of the
        Consortium of Swiss Academic Libraries. The metadata management part (at the level of journal articles) has
        been allocated to the team of the Swissbib project.
    </p>
    <a href="http://www.swissbib.blogspot.ch/2016/03/national-licences-and-article-metadata.html"
       target="_blank" class="btn btn-link" title="Link to blog post">Additional information</a>
</div>