<!-- User have to fill the homePostalAddress in the Swiss edu-Id account -->
<p>
    <span class="text-aligned-icon icon-danger"><i class="fa fa-times"></i></span>
    <?= $this->transEsc('snl.theAddressNotVerifiedYet') ?>
    <a href="https://eduid.ch/web/verify-attribute/?attribute=homepostaladdress"><?= $this->transEsc('snl.theAddressNotVerifiedYet.verify') ?></a>
    <?= $this->transEsc('snl.theAddressNotVerifiedYet.verify2') ?>
</p>