<!-- User have to fill the homePostalAddress in the Swiss edu-Id account -->
<p>
    <span class="text-aligned-icon icon-danger"><i class="fa fa-times"></i></span>
    <?= $this->transEsc('snl.theAddressNotVerifiedYet') ?>
    <a href="https://eduid.ch/web/change-account-data/1/"><?= $this->transEsc('snl.theAddressNotVerifiedYet.verify') ?></a>
    <?= $this->transEsc('snl.theAddressNotVerifiedYet.verify2') ?>

</p>
<p>
    <img src="https://test.swissbib.ch/themes/sbvfrdsingle/images/verify_help.png" class="img-thumbnail image-address-verify-help">
</p>