<div class="home-content-box">
    <h2 class="lead">À propos de jusbib</h2>
    <p>
        jusbib est un méta-catalogue des bibliothèques juridiques suisses et d'autres collections de littérature juridique.
        L'interface et les fonctionnalités de recherche correspondent à celles de swissbib.
    </p>
    <a href="<?= $this->basePath('Libraries') ?>" class="btn btn-link" title="Liste des institutions">Institutions participantes</a>
</div>
