<div class="home-content-box">
    <h2 class="lead">Nouveau design 2015</h2>
    <p>
        jusbib revêt de nouveaux atours au printemps 2015. La nouvelle mise en forme des pages s’adapte de manière dynamique au
        format des divers écrans, pour que vous puissiez utiliser facilement jusbib sur votre smartphone, votre tablette ou votre ordinateur.
    </p>
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.swissbib.blogspot.ch/') ?>" target="_blank"
       class="btn btn-link" title="Link zum Blog">Plus d'informations</a>
</div>

