<div class="home-content-box">
    <h2 class="lead">Codexplo 2.0 - Recherche dans les grands commentaires du CC/CO</h2>
    <p>
        Codexplo permet la recherche des articles dans les grands commentaires du CC/CO (Basler Kommentar, Berner Kommentar, Commentaire romand, Zürcher Kommentar) et offre ainsi la possibilité d’identifier rapidement les différents volumes commentant un article donné.
    </p>
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://lawlibraries.ch/?page_id=1060&lang=fr') ?>" target="_blank"
       class="btn btn-link" title="Link zu Codexplo">Codexplo 2.0</a>
</div>

