<h2 xmlns="http://www.w3.org/1999/html">Jusbib en trois étapes</h2>
<p>
    Jusbib offre un accès rapide, simple et complet à la littérature juridique peu importe qu’elle soit contenue dans des livres,
    des revues, des journaux ou des médias électroniques. Jusbib permet la recherche simultanée notamment dans les fonds de toutes
    les bibliothèques universitaires suisses ainsi que de la bibliothèque nationale suisse.
</p>

<p>
    Ci-après, vous trouverez les explications sur la façon de rechercher les documents qui vous intéressent et ensuite d’y accéder.
</p>

<ol class="list">
    <li><a href="#search">Rechercher</a></li>
    <li><a href="#refine">Trouver</a></li>
    <li><a href="#locate">Sélectionner et commander</a></li>
</ol>
<h2><a name="search"></a>Rechercher</h2>
<div class="floatbox">
    <p>
        Introduisez un ou plusieurs termes de recherche dans le champ de recherche.
    </p>
    <p>
        <em>Un astérisque <strong>*</strong> vous permet de remplacer un <strong>nombre infini</strong> de caractères, par exemple
            pour tenir compte des terminaisons différentes de termes (exemple : locat* pour location, locations, locataire, locataires)</em>
    </p>
    <p>
        <em>Un point d’interrogation <strong>?</strong> vous permet de remplacer <strong>un caractère déterminé</strong>
            afin de tenir compte des différentes façons d’écrire un terme (exemple : europe?n pour européen et pour european)</em>
    </p>
    <p>
        <em>Les guillemets <strong>“...“</strong> vous permettent de rechercher une <strong>expression exacte</strong> (exemple : „aménagement du territoire“).
        </em>
    </p>
</div>

<h2><a name="refine"></a>Trouver</h2>
<div class="floatbox">
    <h3>Affiner la recherche</h3>
    <p>
        Vous pouvez affiner votre résultat de recherche en utilisant les critères contenus dans les filtres proposés dans la
        partie droite de l’écran.
    </p>
    <p>
        Recherche d’un <strong>auteur précis</strong> : <br/>
        Lorsque vous effectuez une recherche à l’aide d’un nom de famille, vous obtenez un résultat qui contient différents
        auteurs portant ce nom. Afin de limiter le résultat à l’auteur qui vous intéresse, vous pouvez le sélectionner dans
        le filtre <strong></strong>auteurs/contributeurs</strong> par un simple clic et ainsi votre résultat ne contiendra
        que les documents de cet auteur.
    </p>
    <p>
        Recherche dans une <strong>matière déterminée</strong> : <br/>
        Dans les filtres <strong>Classification juridique</strong> et <strong>sujet</strong> vous trouvez une liste de matières
        disponibles vous permettant d’affiner votre résultat de recherche par un simple clic de la matière qui vous intéresse.
    </p>
</div>

<h3>Trier le résultat de recherche</h3>
<p>
    Si le tri par <strong>ordre chronologique inverse</strong> (document le plus récent en premier) ne vous convient pas, vous pouvez modifier
    l’ordre de l’affichage des documents à l’aide du bouton Trier par et sélectionner par exemple le tri par &raquo;pertinence&laquo;.
</p>
<h3>Où se procurer les titres intéressants?</h3>
<p>
    Le symbole <i class="fa fa-institution"></i> situé à la droite de chaque titre vous indique quelles bibliothèques possèdent
    le document recherché. Un clic sur la bibliothèque concernée vous donne des informations utiles supplémentaires.
</p>

<h2><a name="locate"></a>Sélectionner et commander</h2>
<div class="floatbox">
    <p>
        Par un clic sur un titre contenu dans le résultat de recherche, on obtient des informations complètes sur ce document
        (titre, auteur, lieu, éditeur, année de parution, nombre de pages, édition, etc.). Sous ces indications se trouve
        une liste des bibliothèques dans lesquelles le titre est disponible. En cliquant sur le symbole <i class="fa fa-heart"></i>
        à côté de la bibliothèque, vous indiquez votre préférence pour cette bibliothèque qui fera partie de vos <strong>favoris</strong>
         ; elle apparaîtra désormais en premier dans la liste des bibliothèques.
    </p>
    <p>
        En cliquant sur le <strong>nom de la bibliothèque</strong>, les indications relatives à la localisation et à la cote du
        document sont affichées. De nombreuses bibliothèques renseignent aussi sur la disponibilité du document.
    </p>

    <h3>Emprunt / commande</h3>
    <p>
        Les documents doivent être empruntés directement auprès de l’une des bibliothèques qui possède le titre. Pour accéder au
        site de cette bibliothèque et y commander ou réserver le document qui vous intéresse, vous pouvez cliquer sur le lien
        <strong>Prêt / Commande</strong> ; vous devrez ensuite introduire les données d’accès à cette bibliothèque.
    </p>
</div>

<h2>Mon jusbib</h2>
<h3>Pourquoi s’inscrire</h3>
<p>
    Une inscription à mon jusbib permet une personnalisation des réglages. Vous pouvez :
</p>
<ul class="list">
    <li>Accéder à des recherches sauvegardées</li>
    <li>Définir des bibliothèques favorites et ensuite les utiliser en permanence</li>
    <li>Enregistrer vos listes de sélection de façon durable</li>
    <li>Configurer les paramètres de l’interface (langue, longueur des listes)</li>
</ul>
<p>
    A <strong>défaut d’inscription</strong>, vous perdez tous les réglages chaque fois que vous fermez le navigateur internet.
</p>

<h2>Fonctionnement de l’inscription à jusbib</h2>
<p>
    Dans jusbib, vous pouvez vous inscrire de deux manières différentes grâce à une gestion des accès supra-régionale :
</p>
<ul class="list">
    <li>
        <strong>switchAAI:</strong> Pour les étudiants et le personnel des universités, des hautes écoles et d’autres institutions,
        l’inscription a lieu par ce service national. Ce service est mis en place par les institutions concernées et est utilisé
        par les étudiants pour l’accès à toutes sortes de services comme à VPN ou à des cours à distance
        (<a href="https://www.switch.ch/fr/services/aai/" target="_blank" title="Info switchAAI">davantage d’informations</a>).
    </li>
    <li>
        <strong>swiss edu-ID:</strong> Ce service nouveau de switch est conçu pour les utilisatrices et utilisateurs qui
        ne sont pas affiliés à une haute école ou université et qui ne peuvent donc pas se connecter en utilisant
        switchAAI
        (<a href="https://projects.switch.ch/eduid/" target="_blank" title="Info sur swiss edu-ID">plus d'informations</a>).
    </li>
</ul>

<h2>Pourquoi quitter la session?</h2>
<p>
    Lorsque vous vous connectez sur un ordinateur public, nous vous recommandons vivement de quitter la session
    <strong>et de fermer le navigateur</strong> afin d’éviter qu’un tiers n’utilise votre compte.
</p>
