<h2>À propos de jusbib</h2>
<p>
    Jusbib est un méta-catalogue de publications provenant de bibliothèques juridiques suisses et d'autres collections juridiques.
    L'interface et les fonctionnalités de recherche correspondent à celles de swissbib - catalogue nationale suisse.
</p>
<p>
    En outre, les données peuvent être interrogées au moyen d'une classification par domaines du droit; la classification choisie
    est le plan systématique multilingue de
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.isdc.ch/d2wfiles/document/5440/4018/0/Plan%20syst%20F%28ISDC%29.pdf') ?>"
       target="_blank">l'Institut Suisse de droit comparé</a>.
</p>
<p>
    Le projet jusbib a été lancé par <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.lawlibraries.ch/') ?>" target="_blank">
        l'Association des bibliothèques juridiques suisses</a> et est réalisé en collaboration avec le groupe de projet swissbib.
    Il reçoit un appui financier de <a href="https://www.bj.admin.ch/bj/fr/home.html" target="_blank">l'Office fédéral de la Justice</a> et de
    l'association <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.svri.ch/index.html') ?>" target="_blank">eJustice.CH</a>.
</p>
