<div class="home-content-box">
    <h2 class="lead">Postversand – Bücher nach Hause schicken lassen</h2>
    <p>Sie haben keine Zeit in der Bibliothek vorbeizukommen? Lassen Sie sich Bücher bequem per Post nach Hause schicken…</p>

    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib-baselbern.blogspot.ch/search/label/Tipp') ?>" target="_blank" class="btn btn-link">Mehr Informationen im Blog</a>

</div>