

<div class="home-content-box">
  <h2 class="lead">Reminders Bern University</h2>
  <p>We are receiving information about a problem concerning reminder mails from Bern University Library transfered to spam folders:</p>
  <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.unibe.ch/university/services/university_library/services/borrowing/index_eng.html') ?>" target="_blank" class="btn btn-link">More info about spam mail</a>

</div>



