<div class="home-content-box">
  <h2 class="lead">Maintenance Work until Monday, 28.4.2016</h2>
  <img class="img-responsive" src="<?= $this->basePath('themes/sbvfrdmulti/images/underconstruction.jpg') ?>" width="250">
  <br/>
  <p>Because of maintenance work the following functionalities aren't available at the moment: "Delete reservations" and "Bookings". We apologize for any inconveniences.</p>
</div>