<div class="home-content-box">
    <h2 class="lead">NEU - CHAT</h2>
    <p><b>Kurze Frage – schnelle Antwort</b>
        <br></br>
        Stellen Sie uns Ihre Frage per Chat und wir antworten Ihnen umgehend.
        Der Chat ist von Montag bis Freitag, 9 bis 17 Uhr, online.</p>
    <div class="row needs-js">
        chat loading...
    </div>
    <div><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib-baselbern.blogspot.ch/search/label/Tipp') ?>" target="_blank" class="btn btn-link">Mehr Informationen im Blog</a></div>
</div>