<div class="home-content-box">
    <h2 class="lead">Neuerungen: Suchergebnisse mit Filtern präzisieren</h2>
    <p>Passen Sie Ihre Suchergebnisse Ihren Bedürfnissen an: Schliessen Sie beispielsweise eine Sprache aus oder suchen Sie gleichzeitig nach verschiedenen Medienformaten.</p>

    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib-baselbern.blogspot.ch/search/label/Tipp') ?>" target="_blank" class="btn btn-link">Mehr Informationen im Blog</a>
</div>