<div class="home-content-box">
  <h2 class="lead">How to get started?</h2>
  <p><a href="http://prezi.com/5htcvti9lnmq/?utm_campaign=share&utm_medium=copy&rc=ex0share" target="_blank" class="btn btn-link">Introducing swissbib Basel Bern</a></p>
  <p><a href="https://tube.switch.ch/videos/8e47b4c8" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> How to search?</a></p>
  <p><a href="https://tube.switch.ch/videos/5cf66034" target="_blank" class="btn btn-link"><i class="fa fa-video-camera"></i> How to order?</a></p>
</div>