<? if ($this->swissLibraryPersonResidence): ?>
    <? if ($this->swissLibraryPersonResidence === 'CH'): ?>
        <p>
            <span class="text-aligned-icon icon-success"><i class="fa fa-check"></i></span>
            <?= $this->transEsc('snl.youHavePostalAddresInSwitzerland') ?>
        </p>
        <a href="<?= $this->url('national-licences') ?>/activate-permanent-access">
            <button class="btn btn-primary" <?= $this->hasAcceptedTermsAndConditions? "" : "disabled"; ?>><?= $this->transEsc('snl.permanentAccess.activate') ?></button>
        </a>
    <? else:; ?>
        <!-- User have a foreign adress -->
        <p>
            <span class="text-aligned-icon icon-danger"><i class="fa fa-times"></i></span>
            <?= $this->transEsc('snl.thisServiceIsOnlyForSwissResidents') ?>
        </p>
    <? endif; ?>
<? else:; ?>
    <? if ($this->homePostalAddress): ?>
        <? if ($this->isHomePostalAddressInSwitzerland): ?>
            <p>
                <span class="text-aligned-icon icon-success"><i class="fa fa-check"></i></span>
                <?= $this->transEsc('snl.youHavePostalAddresInSwitzerland') ?>asd
            </p>
            <a href="<?= $this->url('national-licences') ?>/activate-permanent-access">
                <button class="btn btn-primary" <?= $this->hasAcceptedTermsAndConditions? "" : "disabled"; ?>><?= $this->transEsc('snl.temporaryAccess.activate') ?></button>
            </a>
        <? else:; ?>
            <!-- User have a foreign adress -->
            <p>
                <span class="text-aligned-icon icon-danger"><i class="fa fa-times"></i></span>
                <?= $this->transEsc('snl.thisServiceIsOnlyForSwissResidents') ?>
            </p>
        <? endif; ?>
    <? else:; ?>
        <!-- User have to fill the homePostalAddress in the Swiss edu-Id account -->
        <p>
            <span class="text-aligned-icon icon-danger"><i class="fa fa-times"></i></span>
            <?= $this->transEsc('snl.theAddressNotVerifiedYet') ?>
            <a href="https://eduid.ch/web/change-account-data/1/"><?= $this->transEsc('snl.theAddressNotVerifiedYet.verify') ?></a>
            <?= $this->transEsc('snl.theAddressNotVerifiedYet.verify2') ?>

        </p>
        <p>
            <img src="https://test.swissbib.ch/themes/sbvfrdsingle/images/verify_help.png" class="img-thumbnail image-address-verify-help">
        </p>
    <? endif; ?>
<? endif; ?>