<div class="home-content-box">
    <h2 class="lead">About jusbib</h2>
    <p>
        jusbib is a metacatalogue of Swiss Law Libraries and of other relevant collections of legal literature.
        The interface and search functionalities of jusbib correspond to those of swissbib.
    </p>
    <a href="<?= $this->basePath('Libraries') ?>" class="btn btn-link" title="List of institutions">Participating institutions</a>
</div>
