<div class="home-content-box">
    <h2 class="lead">Redesign 2015</h2>
    <p>
        jusbib was redesigned in Spring 2015. The new Responsive Design enables the use on multiple screen sizes.
        You are now able to use jusbib with full functionality on a smartphone, a tablet or a PC.
    </p>
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.swissbib.blogspot.ch/') ?>" target="_blank"
       class="btn btn-link" title="Link zum Blog">Read more</a>
</div>

