<div class="home-content-box">
    <h2 class="lead">Codexplo 2.0</h2>
        <p>Codexplo enables the search for articles in the comprehensive commentaries of the Swiss civil code/law of obligations (Basler Kommentar, Berner Kommentar, Commentaire romand, Zürcher Kommentar) and thus permits a rapid identification of the different volumes, which comment on a specific article, and where they’re located.
    </p>
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://lawlibraries.ch/?page_id=1060&lang=fr') ?>" target="_blank"
       class="btn btn-link" title="Link zu Codexplo">Codexplo 2.0</a>
</div>

