<div class="home-content-box">
    <h2 class="lead">Fit in swissbib Basel Bern</h2>
    <p>Zum Start des neuen Semesters: Besuchen Sie eine Einführung in "Ihrer" Bibliothek und werden Sie Suchprofi im Bibliothekskatalog swissbib Basel Bern dank vielen Tipps und Tricks.</p>

    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib-baselbern.blogspot.com/2015/09/fit-in-swissbib-basel-bern.html') ?>" target="_blank" class="btn btn-link">Weiterlesen</a>

</div>