<div class="home-content-box">
  <h2 class="lead">Wartungsarbeiten bis Montag, 28.3.2016</h2>
  <img class="img-responsive" src="<?= $this->basePath('themes/sbvfrdmulti/images/underconstruction.jpg') ?>" width="250">
  <br/>
  <p>Wegen Wartungsarbeiten stehen die Funktionen "Reservation löschen" und "Buchung anlegen" zur Zeit nicht zur Verfügung. Wir bitten um Verständnis für die kurze Unterbrechung.</p>
</div>
