<div class="home-content-box">
    <h2 class="lead">Über swissbib.ch Medien bestellen</h2>
    <p>Der IDS-Kurier liefert auch Medien aus Bibliotheken in Zürich, St. Gallen und Luzern an eine Bibliothek in Basel oder Bern. swissbib.ch machts möglich...</p>

    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib-baselbern.blogspot.ch/search/label/Tipp') ?>" target="_blank" class="btn btn-link">Mehr Informationen im Blog</a>

</div>