<div class="home-content-box">
    <h2 class="lead">Kombination von Facetten in der erweiterten Suche</h2>
    <p>Wussten Sie, dass Sie in der erweiterten Suche mehrere Facetten miteinander verbinden können?</p>

    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib-baselbern.blogspot.com/2015/09/kombination-von-facetten-in-der.html') ?>" target="_blank" class="btn btn-link">Weiterlesen</a>

</div>