<div class="home-content-box">
  <h2 class="lead">Wartungsarbeiten bis Sonntag, 22.11.2015, 9:00</h2>
    <img class="img-responsive" src="<?= $this->basePath('themes/sbvfrdmulti/images/underconstruction.jpg') ?>" width="250">
    <br/>
    <p>Wegen Wartungsarbeiten steht Ihre Konto- und Ausleihfunktionen aktuell nicht zur Verfügung. Die Suche ist davon nicht betroffen. Wir bitten um Verständnis für die kurze Unterbrechung.</p>
</div>