<div class="home-content-box">
  <h2 class="lead">Wartungsarbeiten bis Sonntag, 11.9.2016</h2>
  <img class="img-responsive" src="<?= $this->basePath('themes/sbvfrdmulti/images/underconstruction.jpg') ?>" width="230">
  <br/>
  <p>Wegen Wartungsarbeiten kann zur Zeit die Verfügbarkeit von Medien nicht angzeigt werden. Zudem stehen die Funktionen "Reservation löschen" und "Buchung anlegen" nicht zur Verfügung. Wir bitten um Verständnis für die kurze Unterbrechung.</p>
</div>
