<div id="tabbed-tree" class="tabs" role="tabpanel">
  <ul class="recordTabs nav nav-tabs" role="tablist">
    <? $i = 0; ?>
    <? foreach ($classificationTrees as $facetKey => $tree): ?>
      <li <?= $i++ === 0 ? 'class="active"' : '' ?> >
        <a href="#tab-tree-<?= $facetKey ?>"><?= $this->translate($facetKey) ?></a>
      </li>
    <? endforeach ?>
  </ul>
  <div class="tab-content">
  <? $i = 0; ?>
  <? foreach ($classificationTrees as $facetKey => $tree): ?>
    <div id="tab-tree-<?= $facetKey ?>" <?= $i++ === 0 ? 'class="active"' : '' ?> >
      <? echo $this->render(
        'search/advanced/classificationTree',
        array(
          'classificationTree' => $tree,
          'facetKey'           => $facetKey
        )
      );
      ?>
      <div class="clearfix"></div>
    </div>
  <? endforeach ?>
  </div>
</div>