<?
$entry = $classification['entry'];
$hasChildren = count($classification['children']) > 0;
?>
<ul>
  <li data-jstree='{"icon":"fa fa-file"}' data-openChildren='<?= $hasChildren ? 'yes' : 'no' ?>'>
    <a>
      <ins>&nbsp;</ins>
      <input type="hidden" value="<?= $facetKey ?>:&quot;<?= $entry['queryValue'] ?>&quot;">
      <?= $entry['value'] ?> <?= $this->zendTranslate($entry['value'], 'drsys') ?>
      <? if ($entry['nestingLevel'] !== 0 || !$hasChildren): ?>
        (<?= $entry['count'] ?> <?= $this->transEsc('Showing') ?>)
      <? endif; ?>
    </a>
    <? if ($hasChildren): ?>
      <? if ($entry['nestingLevel'] === 0): ?>
        <ul>
            <li data-jstree='{"icon":"fa fa-file"}' data-openChildren='no'>
                <a>
                    <ins>&nbsp;</ins>
                    <input type="hidden" value="<?= $facetKey ?>:&quot;<?= $entry['queryValue'] ?>&quot;">
                    <?= $entry['value'] ?> <?= $this->zendTranslate($entry['value'], 'drsys') ?>
                    (<?= $entry['count'] ?> <?= $this->transEsc('Showing') ?>)
                </a>
            </li>
        </ul>
      <? endif; ?>
      <? foreach ($classification['children'] as $child): ?>
            <?= $this->render(
                'search/advanced/classificationTreeItem',
                array(
                    'classification' => $child,
                    'facetKey'       => $facetKey
                ));
            ?>
      <? endforeach; ?>
    <? endif; ?>
  </li>
</ul>