<?
// Set up page title:
$this->headTitle($this->translate('Bookings'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Bookings') . '</li>';
?>

<div class="<?= $this->layoutClass('mainbody') ?> resultView">
  <h2><?= $this->transEsc('Bookings') ?></h2>
  <?= $this->flashmessages(); ?>


  <?php if( sizeof($this->bookings) ): ?>

      <?
      $headers = [
          'title'         => $this->transEsc('Title'),
          'library_callno' => $this->transEsc('Institution'),
          'pick_up_location'     => $this->transEsc('pick_up_location'),
          'date_from'      => $this->transEsc('date_from'),
          'date_to'        => $this->transEsc('date_to'),
      ];

      $flippedContent = '';
      ?>

      <br />
      <table class="table table-striped hidden-xs hidden-sm">
          <thead>
          <tr>
              <th><?=$headers['title']?></th>
              <th><?=$headers['library_callno']?></th>
              <th><?=$headers['pick_up_location']?></th>
              <th><?=$headers['date_from']?></th>
              <th><?=$headers['date_to']?></th>
          </tr>
          </thead>
          <tbody>

          <?php foreach ($this->bookings as $index => $booking): ?>


          <tr>
              <?
              $flippedContent .= $this->render('myresearch/bookings-flipped.phtml', array(
                  'booking'    => $booking,
                  'headers' => $headers
              ));
              ?>
              <td>
                  <?= $this->escapeHtml($booking['title']) ?>
              </td>
              <td>
                  <? if (!empty($booking['library'])): ?>
                      <?=$this->escapeHtml($booking['library'])?>
                      <br />
                  <? endif; ?>
                  <? if (!empty($booking['callNumber'])): ?>
                      <?=$this->escapeHtml($booking['callNumber'])?>
                  <? endif; ?>
              </td>
              <td>
                  <?=$this->transEsc($booking['pickupLocation']) ?>
              </td>
              <td>
                  <?=date('d/m/y H:i', $booking['dateStart']) ?>
              </td>
              <td>
                  <?=date('d/m/y H:i', $booking['dateEnd']) ?>
              </td>
          </tr>
          <? endforeach; ?>
          </tbody>
      </table>

      <?=$flippedContent;?>

  <?php else: ?>
      <p><?=$this->transEsc('No bookings') ?></p>
  <? endif; ?>
</div>


<div class="<?= $this->layoutClass('sidebar') ?>">
  <?= $this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'bookings')) ?>
</div>