<?
$this->headTitle($this->translate('changeaddress'));

$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
    . '<li class="active">' . $this->transEsc('changeaddress') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
    <h2><?=$this->transEsc('changeaddress') ?></h2>
    <?=$this->flashmessages() ?>

    <?=$this->address?>

<?
    $form = $this->form;
    $form->setAttribute('action', '');
    $form->setAttribute('method', 'post');
    $form->setAttribute('class', 'form-horizontal');
$form->prepare();
    echo $this->form()->openTag($form);
    ?>
    <div class="form_element">
        <?php
        /** @var \Zend\Form\View\Helper\FormElement $name */
        $name = $form->get('name');
        echo $this->formRow($name);
        ?></div>

        <?= $this->render('form/form-group.phtml', ['field' => $form->get('name')]) ?>
    <?= $this->render('form/form-group.phtml', ['field' => $form->get('phoneNumber')]) ?>

    <?= $this->formRow($form->get('submit')); ?>

    <?php echo $this->form()->closeTag() ?>




</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'changeaddress'))?>
</div>
