<?
    // Set up page title:
    $this->headTitle($this->translate('Checked Out Items'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Checked Out Items') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
<h2><?=$this->transEsc('Your Checked Out Items')?></h2>
<?=$this->flashmessages()?>

<? if (!empty($this->transactions)): ?>
  <? if ($this->renewForm): ?>
  <form name="renewals" action="" method="post" id="renewals">
    <div class="toolbar">
      <input type="submit" class="btn btn-default hidden-print" name="renewSelected" value="<?=$this->transEsc("renew_selected")?>" />
<!--          <input type="submit" class="btn btn-default" name="renewAll" value="--><?//=$this->transEsc('renew_all')?><!--" />-->
    </div>
  <? endif; ?>
    <?
    $headers = [
        'title'         => $this->transEsc('Title'),
        'library_callno' => $this->transEsc('Institution'),
        'checkedout'     => $this->transEsc('Checked Out'),
        'renewals'      => $this->transEsc('Renewals'),
        'action',
    ];

    $flippedContent = '';
    ?>

    <br />
    <table class="table table-striped hidden-xs hidden-sm">
    <thead>
    <tr>
        <th><?=$headers['title']?></th>
        <th><?=$headers['library_callno']?></th>
        <th><?=$headers['checkedout']?></th>
        <th><?=$headers['renewals']?></th>
        <th class="hidden-print"><?=$headers['action']?></th>
    </tr>
    </thead>
    <tbody>



  <? $i = 0; foreach ($this->transactions as $resource): ?>
    <? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
        <tr class="<?=$iteration % 2 == 1 ? 'even' : 'odd'?>row">
          <?
          $flippedContent .= $this->render('myresearch/checkedout-flipped.phtml', array(
          'ilsDetails'    => $ilsDetails,
          'renewForm'  => $renewForm,
          'renewResult' => $renewResult,
          'headers' => $headers,
          'even'    => (0 === $iteration % 2)
          ));
          ?>
         <td>
             <?
             // If this is a non-missing Solr record, we should display a link:
             if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                 $title = $resource->getTitle();
                 $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                 echo '<a href="' . $this->recordLink()->getUrl($resource) .
                     '" class="title">' . $title . '</a>';
             } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                 // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                 echo $this->escapeHtml($ilsDetails['title']);
             } else {
                 // Last resort -- indicate that no title could be found.
                 echo $this->transEsc('Title not available');
             }
             ?>
         </td>
         <td>
             <? if (!empty($ilsDetails['library'])): ?> <?=$this->escapeHtml($ilsDetails['library'])?><br />
             <? endif; ?>

             <? if (!empty($ilsDetails['callnum'])): ?> <?=$this->escapeHtml($ilsDetails['callnum'])?>
             <? endif; ?>
         </td>
         <td>
             <?=$this->escapeHtml($ilsDetails['loandate']) ?> <?=$this->transEsc('Due')?> <?=$this->escapeHtml($ilsDetails['duedate'])?><? if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><? endif; ?>
         </td>
         <td>
             <? $isRenewable = $ilsDetails['renewable'];
             if ( $isRenewable )
             {
                 $renewalLimit = preg_replace('/^\d+ \(out of (\d+)\).*$/', '$1', $ilsDetails['renew_info']);
                 if (is_numeric($renewalLimit))
                 {
                     $Renewals = $ilsDetails['renewals'] . ' ' .$this->transEsc('of') . ' ' . $renewalLimit;
                 }
                 else
                 {
                     $renewalInfo = preg_replace('/^\d+ \((.*)\).$/', '$1', $ilsDetails['renew_info']);
                     $Renewals = $ilsDetails['renewals'] . ' (' .$this->translate($renewalInfo) . ')';
                     //$Renewals = $ilsDetails['renew_info'];
                 }
             }
             else
             {
                 $Renewals = $this->translate('no_renewal');
             }
             ?>
             <?=$this->escapeHtml($Renewals)?>
         </td>
         <td>
             <? if ($this->renewForm): ?>
                 <? if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
                     <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
                     <input class="pull-left hidden-print col-xs-1"  type="checkbox" name="renewSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" id="checkbox_<?=$safeId?>" />
                     <input class="pull-left" type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
                 <? endif; ?>
             <? endif; ?>

             <? $showStatus = true; ?>
             <? if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
                 <? $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
                 <? if (isset($renewDetails['success']) && $renewDetails['success']): ?>
                     <? $showStatus = false; ?>
                     <!--            --><?//=$this->transEsc('Due')?><!-- --><?//=$this->escapeHtml($renewDetails['new_date'])?><!-- --><?// if (isset($renewDetails['new_time'])): ?><!----><?//=$this->escapeHtml($renewDetails['new_time'])?><!----><?// endif; ?>
                     <br /><div class="alert alert-success"><?=$this->transEsc('renew_success')?></div>
                 <? else: ?>
                     <!--            --><?//=$this->transEsc('Due')?><!-- --><?//=$this->escapeHtml($ilsDetails['duedate'])?><!----><?// if (isset($ilsDetails['dueTime'])): ?><!-- --><?//=$this->escapeHtml($ilsDetails['dueTime'])?><!----><?// endif; ?>
                     <br /><div class="alert alert-danger"><?=$this->transEsc('renew_fail')?><? //if (isset($renewDetails['sysMessage'])): ?> <?//=$this->escapeHtml($renewDetails['sysMessage'])?><? //endif; ?></div>
                 <? endif; ?>
             <? else: ?>
                 <!--          --><?//=$this->transEsc('Due')?><!-- --><?//=$this->escapeHtml($ilsDetails['duedate'])?><!----><?// if (isset($ilsDetails['dueTime'])): ?><!-- --><?//=$this->escapeHtml($ilsDetails['dueTime'])?><!----><?// endif; ?><!--<br />-->
                 <? if ($showStatus): ?>
                     <? if (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == "overdue"): ?>
                         <br /><div class="alert alert-danger"><?=$this->transEsc("renew_item_overdue")?></div>
                     <? elseif (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == "due"): ?>
                         <br /><div class="alert alert-info"><?=$this->transEsc("renew_item_due")?></div>
                     <? endif; ?>
                 <? endif; ?>
             <? endif; ?>

         </td>


        </tr>

<? endforeach; ?>
    </tbody>
    </table>
    <?=$flippedContent;?>
    <? if ($this->renewForm): ?></form><? endif; ?>

<? else: ?>
    <?=$this->transEsc('You do not have any items checked out')?>.
<? endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'checkedout'))?>
</div>