<?
/** @var array $headers */
/** @var mixed $ilsDetails */
/** @var mixed $resource */
/** @var Boolean $even */
?>
<table class="table table-flipped hidden-md hidden-lg <?= 'table-' . ($even ? 'even' : 'odd') ?>">
    <tbody>
    <tr>
        <th><?=$headers['title']?></th>
        <td><?
            // If this is a non-missing Solr record, we should display a link:
            if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                $title = $resource->getTitle();
                $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                echo '<a href="' . $this->recordLink()->getUrl($resource)
                . '" class="title">' . $title . '</a>';
            } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                echo $this->escapeHtml($ilsDetails['title']);
            } else {
                // Last resort -- indicate that no title could be found.
                echo $this->transEsc('Title not available');
            }
            ?>
        </td>
    </tr>
    <tr>
        <th><?=$headers['library_callno']?></th>
        <td>
            <? if (!empty($ilsDetails['institution'])): ?>
                <?=$this->escapeHtml($this->zendTranslate($ilsDetails['institution'], 'institution'))?>,
            <? endif; ?>

            <? if (!empty($ilsDetails['signature'])): ?>
                <?=$this->escapeHtml($ilsDetails['signature'])?>
            <? endif; ?>
        </td>
    </tr>
    <tr>
        <th><?=$headers['pick_up_location']?></th>
        <td>
            <? /* Depending on the ILS driver, the "location" value may be a string or an ID; figure out the best
           value to display... */ ?>
            <? $pickupDisplay = ''; ?>
            <? $pickupTranslate = false; ?>
            <? if (isset($ilsDetails['location'])): ?>
                <? if ($this->pickup): ?>
                    <? foreach ($this->pickup as $library): ?>
                        <? if ($library['locationID'] == $ilsDetails['location']): ?>
                            <? $pickupDisplay = $library['locationDisplay']; ?>
                            <? $pickupTranslate = true; ?>
                        <? endif; ?>
                    <? endforeach; ?>
                <? endif; ?>
                <? if (empty($pickupDisplay)): ?>
                    <? $pickupDisplay = $ilsDetails['location']; ?>
                <? endif; ?>
            <? endif; ?>
            <? if (!empty($pickupDisplay)): ?>
                <?=$pickupTranslate ? $this->transEsc($pickupDisplay) : $this->escapeHtml($pickupDisplay)?>
            <? endif; ?>
        </td>
    </tr>
    <tr>
        <th><?=$headers['created']?></th>
        <td>
            <?=$this->escapeHtml($ilsDetails['create']) ?>
        </td>
    </tr>
    <tr>
        <th><?=$headers['status']?></th>
        <td>
            <?if (preg_match('/due date/', $ilsDetails['status']))
            {
                $status = $this->transEsc('Waiting in queue') . ': ' . $ilsDetails['position'] . '; ' .
                    $this->transEsc('Due Date') . ': ' . $ilsDetails['duedate'];
            }
            elseif (preg_match('/queue$/', $ilsDetails['status']))
            {
                $status = $this->transEsc('Waiting in queue') . ': ' . $ilsDetails['position'];
            }
            elseif (preg_match('/On hold until:/', $ilsDetails['status']))
            {
            $status = $this->transEsc('On hold until') . ': ' . preg_replace('/On hold until: /', '',  $ilsDetails['status']);
            }
            else
            {
                $status = $this->transEsc($ilsDetails['status']);
            }
            ?>
            <?=$this->escapeHtml($status)?>
        </td>
    </tr>
    <? if ($this->cancelForm && isset($ilsDetails['cancel_details']) || (isset($this->cancelResults['items']))): ?>
    <tr>
        <th><?= isset($headers['action']) ? $headers['action'] : '' ?></th>
        <td>
            <? if ($this->cancelForm && isset($ilsDetails['cancel_details'])): ?>
                <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $resource->getUniqueId()); ?>
                <input type="hidden" name="cancelAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" />
                <div class="pull-left">
                    <input type="checkbox" name="cancelSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" id="checkbox_<?=$safeId?>" />
                </div>
            <? endif; ?>

            <? if (isset($this->cancelResults['items'])): ?>
                <? foreach ($this->cancelResults['items'] as $itemId=>$cancelResult): ?>
                    <? if ($itemId == $ilsDetails['item_id'] && $cancelResult['success'] == false): ?>
                        <br /><div class="alert alert-danger"><?=$this->transEsc($cancelResult['status']) ?><? if ($cancelResult['sysMessage']) echo ' : ' . $this->transEsc($cancelResult['sysMessage']); ?></div>
                    <? endif; ?>
                <? endforeach; ?>
            <? endif; ?>

            <? if (isset($ilsDetails['available']) && $ilsDetails['available'] == true): ?>
                <br /><div class="text-success"><?=$this->transEsc("hold_available") ?></div>
            <? endif; ?>
            <? if (isset($ilsDetails['cancel_link'])): ?>
                <p><a href="<?=$this->escapeHtmlAttr($ilsDetails['cancel_link']) ?>"><?=$this->transEsc("hold_cancel") ?></a></p>
            <? endif; ?>
        </td>
    </tr>
    <? endif; ?>
    </tbody>
</table>