<?
    // Set up page title:
    $this->headTitle($this->translate('My Holds'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('My Holds') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
<h2><?=$this->transEsc('Your Holds and Recalls') ?></h2>

<?=$this->flashmessages()?>

<? if (!empty($this->recordList)): ?>
  <? if ($this->cancelForm): ?>
    <form name="cancelForm" class="inline" action="" method="post" id="cancelHold">
      <input type="hidden" id="submitType" name="cancelSelected" value="1"/>
      <input type="hidden" id="cancelConfirm" name="confirm" value="0"/>
      <div class="btn-group">
        <input id="cancelSelected" name="cancelSelected" type="submit" value="<?=$this->transEsc("hold_cancel_selected") ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown"/>
        <ul class="dropdown-menu">
          <li class="disabled"><a><?=$this->transEsc("confirm_hold_cancel_selected_text") ?></a></li>
          <li><a href="#" onClick="$('#cancelConfirm').val(1);$('#submitType').attr('name','cancelSelected');$(this).parents('form').submit(); return false;"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
          <li><a href="#" onClick="return false;"><?=$this->transEsc('confirm_dialog_no')?></a></li>
        </ul>
      </div>
      <!--<div class="btn-group">
        <input id="cancelAll" name="cancelAll" type="submit" value="<?/*=$this->transEsc("hold_cancel_all") */?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown"/>
        <ul class="dropdown-menu">
          <li class="disabled"><a><?/*=$this->transEsc("confirm_hold_cancel_all_text") */?></a></li>
          <li><a href="#" onClick="$('#cancelConfirm').val(1);$('#submitType').attr('name','cancelAll');$(this).parents('form').submit(); return false;"><?/*=$this->transEsc('confirm_dialog_yes') */?></a></li>
          <li><a href="#" onClick="return false;"><?/*=$this->transEsc('confirm_dialog_no')*/?></a></li>
        </ul>
      </div>-->
  <? endif; ?>

    <?
    $headers = [
        'title'         => $this->transEsc('Title'),
        'library_callno' => $this->transEsc('Institution'),
        'pick_up_location'     => $this->transEsc('pick_up_location'),
        'created'      => $this->transEsc('Created'),
        'status'        => $this->transEsc('Status'),
        'action',
    ];

    $flippedContent = '';
    ?>

    <br /><br />
    <table class="table table-striped hidden-xs hidden-sm">
    <thead>
    <tr>
        <th><?=$headers['title']?></th>
        <th><?=$headers['library_callno']?></th>
        <th><?=$headers['pick_up_location']?></th>
        <th><?=$headers['created']?></th>
        <th><?=$headers['status']?></th>
        <th class="hidden-print"><?=$headers['action']?></th>
    </tr>
    </thead>
    <tbody>

  <? $iteration = 0; ?>
  <? foreach ($this->recordList as $resource): ?>
    <? $iteration++; ?>
    <? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
        <tr class="<?=$iteration % 2 == 1 ? 'even' : 'odd'?>row">
            <?
            $flippedContent .= $this->render('myresearch/holds-flipped.phtml', array(
                'ilsDetails'    => $ilsDetails,
                'resource'   => $resource,
                'cancelForm'  => $this->cancelForm,
                'cancelResults' => $this->cancelResults,
                'headers' => $headers,
                'even'    => (0 === $iteration % 2)
            ));
            ?>
            <td><?
                // If this is a non-missing Solr record, we should display a link:
                if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                    $title = $resource->getTitle();
                    $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                    echo '<a href="' . $this->recordLink()->getUrl($resource)
                        . '" class="title">' . $title . '</a>';
                } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                    // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                    echo $this->escapeHtml($ilsDetails['title']);
                } else {
                    // Last resort -- indicate that no title could be found.
                    echo $this->transEsc('Title not available');
                }
                ?>
            </td>
            <td>
                <? if (!empty($ilsDetails['institution'])): ?>
                    <?=$this->escapeHtml($this->zendTranslate($ilsDetails['institution'], 'institution'))?>
                    <br />
                <? endif; ?>

                <? if (!empty($ilsDetails['signature'])): ?>
                    <?=$this->escapeHtml($ilsDetails['signature'])?>
                <? endif; ?>
            </td>
            <td>
                <? /* Depending on the ILS driver, the "location" value may be a string or an ID; figure out the best
           value to display... */ ?>
                <? $pickupDisplay = ''; ?>
                <? $pickupTranslate = false; ?>
                <? if (isset($ilsDetails['location'])): ?>
                    <? if ($this->pickup): ?>
                        <? foreach ($this->pickup as $library): ?>
                            <? if ($library['locationID'] == $ilsDetails['location']): ?>
                                <? $pickupDisplay = $library['locationDisplay']; ?>
                                <? $pickupTranslate = true; ?>
                            <? endif; ?>
                        <? endforeach; ?>
                    <? endif; ?>
                    <? if (empty($pickupDisplay)): ?>
                        <? $pickupDisplay = $ilsDetails['location']; ?>
                    <? endif; ?>
                <? endif; ?>
                <? if (!empty($pickupDisplay)): ?>
                    <?=$pickupTranslate ? $this->transEsc($pickupDisplay) : $this->escapeHtml($pickupDisplay)?>
                <? endif; ?>
            </td>
            <td>
                <?=$this->escapeHtml($ilsDetails['create']) ?>
            </td>
            <td>
                <?if (preg_match('/due date/', $ilsDetails['status']))
                {
                    $status = $this->transEsc('Waiting in queue') . ': ' . $ilsDetails['position'] . '; ' .
                        $this->transEsc('Due Date') . ': ' . $ilsDetails['duedate'];
                }
                elseif (preg_match('/queue$/', $ilsDetails['status']))
                {
                    $status = $this->transEsc('Waiting in queue') . ': ' . $ilsDetails['position'];
                }
                else
                {
                    $status = $this->transEsc($ilsDetails['status']);
                }
                ?>
                <?=$this->escapeHtml($status)?>
            </td>
            <td>
                <? if ($this->cancelForm && isset($ilsDetails['cancel_details'])): ?>
                    <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $resource->getUniqueId()); ?>
                    <input type="hidden" name="cancelAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" />
                    <div class="pull-left">
                        <input type="checkbox" name="cancelSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" id="checkbox_<?=$safeId?>" />
                    </div>
                <? endif; ?>

                <? if (isset($this->cancelResults['items'])): ?>
                    <? foreach ($this->cancelResults['items'] as $itemId=>$cancelResult): ?>
                        <? if ($itemId == $ilsDetails['item_id'] && $cancelResult['success'] == false): ?>
                            <br /><div class="alert alert-danger"><?=$this->transEsc($cancelResult['status']) ?><? if ($cancelResult['sysMessage']) echo ' : ' . $this->transEsc($cancelResult['sysMessage']); ?></div>
                        <? endif; ?>
                    <? endforeach; ?>
                <? endif; ?>

                <? if (isset($ilsDetails['available']) && $ilsDetails['available'] == true): ?>
                    <br /><div class="text-success"><?=$this->transEsc("hold_available") ?></div>
                <? endif; ?>
                <? if (isset($ilsDetails['cancel_link'])): ?>
                    <p><a href="<?=$this->escapeHtmlAttr($ilsDetails['cancel_link']) ?>"><?=$this->transEsc("hold_cancel") ?></a></p>
                <? endif; ?>
            </td>
    </tr>
    <? endforeach; ?>

        </tbody>
    </table>
    <?=$flippedContent;?>
    <? if ($this->cancelForm): ?></form><? endif; ?>
<? else: ?>
    <?=$this->transEsc('You do not have any holds or recalls placed') ?>.
<? endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
<?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'holds'))?>
</div>