<h1>IDS-Kurierdienst</h1>
<p>Medien aus IDS-Kurierbibliotheken können zum Abholen an alle anderen IDS-Kurierbibliotheken bestellt werden und an jeder IDS-Kurierbibliothek auch zurückgebracht werden:</p>
<ul>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken/a100/?S=1') ?>" target="_blank">Basel UB Hauptbibliothek</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken/a140/?S=1') ?>" target="_blank">Basel UB Medizin</a> (nur Bestellungen nach Bern)</li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken/a125/?S=1') ?>" target="_blank">Basel UB Wirtschaft - SWA</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://unibe.ch/universitaet/dienstleistungen/universitaetsbibliothek/teilbibliotheken/berner_ids_bibliotheken/b404/index_ger.html') ?>" target="_blank">Bern UB Bibliothek Münstergasse</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://unibe.ch/universitaet/dienstleistungen/universitaetsbibliothek/teilbibliotheken/berner_ids_bibliotheken/b410/index_ger.html') ?>" target="_blank">Bern UB Basisbibliothek Unitobler</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://unibe.ch/universitaet/dienstleistungen/universitaetsbibliothek/teilbibliotheken/berner_ids_bibliotheken/b500/index_ger.html') ?>" target="_blank">Bern UB Bibliothek vonRoll</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://unibe.ch/universitaet/dienstleistungen/universitaetsbibliothek/teilbibliotheken/berner_ids_bibliotheken/b452/index_ger.html') ?>" target="_blank">Bern UB Fachbereichsbibliothek Bühlplatz</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://unibe.ch/universitaet/dienstleistungen/universitaetsbibliothek/teilbibliotheken/berner_ids_bibliotheken/b465/index_ger.html') ?>" target="_blank">Bern UB Juristische Bibliothek</a> (nur Abholort)</li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://unibe.ch/universitaet/dienstleistungen/universitaetsbibliothek/teilbibliotheken/berner_ids_bibliotheken/b415/index_ger.html') ?>" target="_blank">Bern UB Schweizerische Osteuropabibliothek</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('https://www.phbern.ch/schule-und-weiterbildung/mediothek-und-medienbildung.html') ?>" target="_blank">Bern PH Weiterbildung und Medienbildung</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zhbluzern.ch/index.php?id=1218') ?>" target="_blank">Luzern Zentral- und Hochschulbibliothek Sempacherstrasse</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zhbluzern.ch/index.php?id=1219') ?>" target="_blank">Luzern Zentral- und Hochschulbibliothek UNI/PH-Gebäude</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zhbluzern.ch/standorte/hochschule-luzern-wirtschaft/') ?>" target="_blank">Luzern Zentral- und Hochschulbibliothek Wirtschaft</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.unisg.ch/wissen/bibliothek') ?>" target="_blank">St. Gallen HSG</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.sg.ch/home/kultur/kantonsbibliothek.html') ?>" target="_blank">St. Gallen Kantonsbibliothek Vadiana</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zb.uzh.ch') ?>" target="_blank">Zürich Zentralbibliothek</a></li>
</ul>

<p><strong>Kosten:</strong> Fr. 5.- pro Dokument. Barzahlung bei Abholung. Für nicht abgeholte Dokumente wird der Tarif trotzdem in Rechnung gestellt.</p>
<p><strong>Lieferfrist:</strong> Die von Ihnen online bestellten Dokumente werden vom IDS-Kurier täglich (ohne Samstag) abgeholt und im Normalfall innerhalb von zwei Arbeitstagen an die gewünschte Abholbibliothek geliefert. Dort bleiben die Medien während einer Woche zum Abholen bereitgestellt.</p>
