<h1>IDS-Kurierdienst</h1>
<p>Medien aus IDS-Kurierbibliotheken können zum Abholen an alle anderen IDS-Kurierbibliotheken bestellt werden und an jeder IDS-Kurierbibliothek auch zurückgebracht werden:</p>
<ul>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('https://www.ag.ch/de/bks/kultur/archiv_bibliothek/kantonsbibliothek/kantonsbibliothek.jsp') ?>" target="_blank">Aarau, Aargauer Kantonsbibliothek</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken/a100/?S=1') ?>" target="_blank">Basel UB Hauptbibliothek</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken/a140/?S=1') ?>" target="_blank">Basel UB Medizin</a> (nur Bestellungen nach Bern)</li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken/a125/?S=1') ?>" target="_blank">Basel UB Wirtschaft - SWA</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://unibe.ch/universitaet/dienstleistungen/universitaetsbibliothek/teilbibliotheken/berner_ids_bibliotheken/b404/index_ger.html') ?>" target="_blank">Bern UB Bibliothek Münstergasse</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://unibe.ch/universitaet/dienstleistungen/universitaetsbibliothek/teilbibliotheken/berner_ids_bibliotheken/b410/index_ger.html') ?>" target="_blank">Bern UB Basisbibliothek Unitobler</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://unibe.ch/universitaet/dienstleistungen/universitaetsbibliothek/teilbibliotheken/berner_ids_bibliotheken/b500/index_ger.html') ?>" target="_blank">Bern UB Bibliothek vonRoll</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://unibe.ch/universitaet/dienstleistungen/universitaetsbibliothek/teilbibliotheken/berner_ids_bibliotheken/b452/index_ger.html') ?>" target="_blank">Bern UB Fachbereichsbibliothek Bühlplatz</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://unibe.ch/universitaet/dienstleistungen/universitaetsbibliothek/teilbibliotheken/berner_ids_bibliotheken/b465/index_ger.html') ?>" target="_blank">Bern UB Juristische Bibliothek</a> (nur Abholort)</li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://unibe.ch/universitaet/dienstleistungen/universitaetsbibliothek/teilbibliotheken/berner_ids_bibliotheken/b415/index_ger.html') ?>" target="_blank">Bern UB Schweizerische Osteuropabibliothek</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL(' https://www.phbern.ch/schule-und-weiterbildung/mediothek.html') ?>" target="_blank">Bern PH Weiterbildung und Medienbildung</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('https://www.hslu.ch/de-ch/technik-architektur/campus/bibliothek/') ?>" target="_blank">Luzern, Hochschule Luzern - Bibliothek Technik & Architektur</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('https://www.hslu.ch/de-ch/design-kunst/ueber-uns/kunst-und-designbibliothek/') ?>" target="_blank">Luzern, Hochschule Luzern - Kunst- und Designbibliothek</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('https://www.hslu.ch/de-ch/soziale-arbeit/campus/mediothek/') ?>" target="_blank">Luzern, Hochschule Luzern - Mediothek Soziale Arbeit</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('https://www.hslu.ch/de-ch/musik/campus/bibliothek/') ?>" target="_blank">Luzern, Hochschule Luzern – Musikbibliothek</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zhbluzern.ch/index.php?id=1218') ?>" target="_blank">Luzern, Zentral- und Hochschulbibliothek Sempacherstrasse</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zhbluzern.ch/index.php?id=1219') ?>" target="_blank">Luzern, Zentral- und Hochschulbibliothek UNI/PH-Gebäude</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zhbluzern.ch/standorte/hochschule-luzern-informatik/') ?>" target="_blank">Luzern, Zentral- und Hochschulbibliothek, Bibliothek Hochschule Luzern – Informatik</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zhbluzern.ch/standorte/hochschule-luzern-wirtschaft/') ?>" target="_blank">Luzern, Zentral- und Hochschulbibliothek Wirtschaft</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.unisg.ch/wissen/bibliothek') ?>" target="_blank">St. Gallen, HSG</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.sg.ch/home/kultur/kantonsbibliothek.html') ?>" target="_blank">St. Gallen, Kantonsbibliothek Vadiana</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zb.uzh.ch') ?>" target="_blank">Zürich, Zentralbibliothek</a></li>
</ul>

<p><strong>Kosten:</strong> Fr. 5.- pro Dokument. Barzahlung bei Abholung. Für nicht abgeholte Dokumente wird der Tarif trotzdem in Rechnung gestellt.</p>
<p><strong>Lieferfrist:</strong> Die von Ihnen online bestellten Dokumente werden vom IDS-Kurier täglich (ohne Samstag) abgeholt und im Normalfall innerhalb von zwei Arbeitstagen an die gewünschte Abholbibliothek geliefert. Dort bleiben die Medien während einer Woche zum Abholen bereitgestellt.</p>

<h1>Kopienversand</h1>
<p><strong>Kosten:</strong> Bezug aus der Schweiz (Privatpersonen) pro 20 Seiten Fr. 5.- </p>
<p><strong>Bearbeitungszeit:</strong> Montag bis Freitag innerhalb 24 Stunden. <br>
Siehe detailliertere Informationen unter:
<a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/ub-hauptbibliothek/dienstleistungen/kopienversand/') ?>" target="_blank">Kopienversand Basel</a> /
<a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.unibe.ch/universitaet/dienstleistungen/universitaetsbibliothek/service/ausleihe/fernleihe___document_delivery/index_ger.html') ?>" target="_blank">Kopienversand Bern</a> </p>