<h1>FAQ</h1>
<nav>
    <ul>
        <li><a href="#q1">Was ist der kürzeste Weg zur Übersicht meiner Ausleihen?</a>
        <li><a href="#q2">Kann ich im Bestand einer bestimmten Bibliothek suchen?</a></li>
        <li><a href="#q3">Können Sie mir ein bestimmtes Medium per Post senden?</a></li>
        <li><a href="#q4">Warum funktioniert der Link zum Volltext bei E-Books und Artikeln nicht immer?</a></li>
        <li><a href="#q5">Kann ich Resultate in Literaturverwaltungsprogramme exportieren?</a></li>
        <li><a href="#q6">Das Richtige nicht gefunden?</a></li>
        <li><a href="#q7">Wo kann ich sonst noch suchen?</a></li>
        <li><a href="#q8">Ist Ihre Frage nicht dabei?</a></li>
    </ul>
</nav>
<br />
<dl>
    <dt><a name="q1"></a>Was ist der kürzeste Weg zur Übersicht meiner Ausleihen?</dt>
    <dd><p><a href="<?= $this->url('myresearch-userlogin') ?>">Anmelden</a>, dann auf My swissbib klicken (oben rechts).</p></dd>
    <dt><a name="q2"></a>Kann ich im Bestand einer bestimmten Bibliothek suchen?</dt>
    <dd><p>Ihre Suchergebnisse lassen sich rechts unter Suche verfeinern nach der gewünschten Bibliothek eingrenzen. Alternativ können Sie die Bibliothek in der Erweiterten Suche auswählen. Bibliotheken können als sogenannte <a href="<?=$this->url('myresearch-favorite-institutions')?>"><?=$this->transEsc('mylibraries')?></a> unter My swissbib dauerhaft gespeichert werden.</p></dd>
    <dt><a name="q3"></a>Können Sie mir ein bestimmtes Medium per Post senden?</dt>
    <dd><p>Einige Bibliotheken schicken Ihnen die Medien an Ihre Postadresse oder zum Abholen an eine von Ihnen gewünschte Bibliothek. Nach erfolgter Anmeldung klicken Sie beim gewünschten Titel unter Exemplar auf Bestellen: je nach Bibliothek werden unterschiedliche Abholstandorte angeboten. Siehe Details unter <a href="<?= $this->url('help-page', array('topic' => 'delivery')); ?>"><?= $this->transEsc('helppage.delivery') ?></a>.</p></dd>
    <dt><a name="q4"></a>Warum funktioniert der Link zum Volltext bei E-Books und Artikeln nicht immer?</dt>
    <dd><p>Der Zugang zum Volltext funktioniert oft nur aus dem Netz der Universität, die den Inhalt lizenziert hat.</p></dd>
    <dd><p>Als Universitätsangehörige melden Sie sich über VPN (<a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://mobile.unibas.ch') ?>" target="_blank">Basel</a>, <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://unibe.ch/universitaet/campus__und__infrastruktur/rund_um_computer/internetzugang/zugang_auf_interne_ressourcen_mit_vpn/index_ger.html') ?>" target="_blank">Bern</a>) an, wenn Sie sich nicht auf dem Campus befinden, und schränken Sie Ihre Suchergebnisse auf der rechten Seite mit dem Filter Uni Basel online bzw. Uni Bern online ein.</p></dd>
    <dt><a name="q5"></a>Kann ich Resultate in Literaturverwaltungsprogramme exportieren?</dt>
    <dd><p>Ja. Klicken Sie entweder auf der Ebene der Suchergebnisse oder auf der Ebene des einzelnen Titels auf das Export-Symbol <i class="fa fa-share"></i>.</p></dd>
    <dt><a name="q6"></a>Das Richtige nicht gefunden?</dt>
    <dd>
        <ul>
            <li>Erweitern Sie Ihre Suche auf <a href="https://www.swissbib.ch" target="_blank" title="swissbib">swissbib.ch</a> (ganze Schweiz) und bestellen Sie bequem aus <a href="<?= $this->url('help-page', array('topic' => 'delivery')); ?>">IDS-Kurierbibliotheken</a>.</li>
            <li>Schicken Sie uns Ihren Fernleihauftrag: Bestellformular <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/ub-hauptbibliothek/dienstleistungen/ausleihe/kurier-und-fernleihe/fernleihformular') ?>" target="_blank">UB Basel</a> / <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.unibe.ch/universitaet/dienstleistungen/universitaetsbibliothek/service/ausleihe/fernleihe___document_delivery/bestellformular/index_ger.html') ?>" target="_blank">UB Bern</a></li>
            <li>Schicken Sie uns Ihren Anschaffungsvorschlag: <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/ub-hauptbibliothek/dienstleistungen/ausleihe/anschaffungsvorschlag') ?>" target="_blank">UB Basel</a> / <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://unibe.ch/universitaet/dienstleistungen/universitaetsbibliothek/service/ausleihe/anschaffungsvorschlaege/index_ger.html') ?>" target="_blank">UB Bern</a></li>
        </ul>
    </dd>
    <dt><a name="q7"></a>Wo kann ich sonst noch suchen?</dt>
    <dd>
        <ul>
            <li><a href="https://www.swissbib.ch" target="_blank" title="swissbib">swissbib</a>: Bestände aller Schweizer Hochschulbibliotheken</li>
            <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://aleph.unibas.ch/F?con_lng=GER&func=find-b-0') ?>" target="_blank" title="swissbib">Katalog IDS Basel Bern</a>: für die Suche nach gewissen Spezialbeständen (historisches Material, Musikalien) empfohlen</li>
            <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://aleph.unibas.ch/F/?func=option-update-lng&file_name=find-b&p_con_lng=GER&local_base=dsv05') ?>" target="_blank" title="swissbib">Verbundkatalog HAN</a>: Verzeichnis für Handschriften, Archive und Nachlässe (Appenzell Ausserrhoden, Basel, Bern, Luzern, Solothurn und St.Gallen)</li>
        </ul>
    </dd>
    <dt><a name="q8"></a>Ist Ihre Frage nicht dabei?</dt>
    <dd><p>Gerne unterstützen wir Sie bei der Recherche und beim Bestellen in unserem Katalog oder nehmen Ihre Anregungen und Kritik entgegen:</p>
        <ul>
            <li>Fragen zu Ihrem Konto oder zu bestimmten Medien: Wenden Sie sich bitte an Ihre Stammbibliothek bzw. die <a href="<?= $this->basePath('Libraries') ?>" title="Liste der Institutionen">Bibliothek</a>, die das Medium besitzt.</li>
            <li>Ihre Fragen sowie Anregungen zu swissbib Basel Bern nehmen wir gerne über das <a href="<?= $this->url('feedback-home') ?>">Kontaktformular</a> oder via <a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#115;&#119;&#105;&#115;&#115;&#98;&#105;&#98;&#45;&#98;&#97;&#115;&#101;&#108;&#98;&#101;&#114;&#110;&#64;&#117;&#110;&#105;&#98;&#97;&#115;&#46;&#99;&#104;">&#115;&#119;&#105;&#115;&#115;&#98;&#105;&#98;&#45;&#98;&#97;&#115;&#101;&#108;&#98;&#101;&#114;&#110; &#97;&#116; &#117;&#110;&#105;&#98;&#97;&#115;&#46;&#99;&#104;</a> entgegen.</li>
        </ul>
    </dd>
</dl>