<h1>Suchen</h1>

<h2>Suchbegriffe kombinieren</h2>
<p>Boolsche Operatoren (AND, OR, NOT) erlauben es, Suchbegriffe logisch miteinander zu verknüpfen. Boolsche Operatoren werden groß geschrieben.</p>
<table class="table table-striped">
    <tbody>
    <tr>
        <td><i>joyce ulysses</i></td>
        <td>Beide Begriffe kommen vor</td>
    </tr>
    <tr>
        <td><i>joyce AND ulysses</i></td>
        <td>Beide Begriffe kommen im selben Feld vor</td>
    </tr>
    <tr>
        <td><i>joyce OR ulysses</i></td>
        <td>Einer der beiden Begriffe kommt vor</td>
    </tr>
    <tr>
        <td><i>joyce NOT ulysses</i></td>
        <td><i>joyce</i> kommt vor, nicht aber <i>ulysses</i></td>
    </tr>
    <tr>
        <td>Komplexere Kombinationen</td>
        <td>Siehe <a class="help-link" href="<?=$this->url('help-home')?>?topic=search" title="<?=$this->transEsc('Help with Search Operators')?>"><?=$this->transEsc("Help with Search Operators")?></a>.
        </td>
    </tr>
    </tbody>
</table>
<br />
<h2>Phrasensuche mit Anführungszeichen</h2>

<table class="table table-striped">
    <tbody>
    <tr>
        <td><i>"street art"</i></td>
        <td>Die beiden Wörter müssen direkt hintereinander stehen.</td>
    </tr>
    <tr>
        <td><i>"street art"~5</i></td>
        <td>Die beiden Wörter müssen innerhalb von 5 Wörtern Abstand vorkommen.</td>
    </tr>
    <tr>
        <td><i>"PZB E 62 2:6"</i></td>
        <td>Signatur</td>
    </tr>
    </tbody>
</table>
<br />
<h2>Platzhalter</h2>

<table class="table table-striped">
    <tbody>
    <tr>
        <td rowspan="2">*</td>
        <td rowspan="2">ersetzt beliebig viele Zeichen</td>
        <td><i>cultur*</i></td>
        <td>culture, cultura, cultural, culturally etc.</td>
    </tr>
    <tr>
        <td><i>Fr*ib*urg</i></td>
        <td>Fribourg, Freiburg etc.</td>
    </tr>
    <tr>
        <td rowspan="2">?</td>
        <td rowspan="2">ersetzt genau ein Zeichen</td>
        <td><i>wom?n</i></td>
        <td>woman, women etc.</td>
    </tr>
    <tr>
        <td><i>Lind??ist</i></td>
        <td>Lindquist, Lindkvist, Lindqvist ecc.</td>
    </tr>
    <tr>
        <td>~</td>
        <td>wenn Sie die genaue<br/>Schreibweise nicht kennen</td>
        <td><i>Tschaikowski~</i></td>
        <td>Tschaikowski, Tchaïkovski, Čajkovskij etc.</td>
    </tr>
    </tbody>
</table>