<div class="home-content-box">
    <h2 class="lead">Suchergebnisse einschränken</h2>
    <p>Verfeinern Sie Ihre Suchergebnisse nach Ihren Bedürfnissen: schränken Sie sie beispielsweise auf bestimmte Medienformate und/oder auf die Bestände einer häufig genutzten Bibliothek ein.</p>

    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib-baselbern.blogspot.ch/search/label/Tipp') ?>" target="_blank" class="btn btn-link">Mehr Informationen im Blog</a>

</div>