<div class="home-content-box">
  <h2 class="lead">Travaux de maintenance, jusqu'à Dimanche, 11.9.2016</h2>
  <img class="img-responsive" src="<?= $this->basePath('themes/sbvfrdmulti/images/underconstruction.jpg') ?>" width="230">
  <br/>
  <p>En raison de travaux de maintenance la disponibilité des documents et les fonctions suivantes ne sont pas disponibles: pré-réservations et annuler des réservations. Veuillez nous excuser pour tout désagrément causé.</p>
</div>
