<div class="home-content-box">
    <h2 class="lead">swissbib Basel Bern hat einen neuen Hilfebereich</h2>
    <p>Die <a href="<?= $this->url('help-page', array('topic' => 'faq')); ?>">neuen FAQs</a> helfen Ihnen bei Fragen weiter - übersichtlich und prägnant.</p>

    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib-baselbern.blogspot.ch/search/label/Tipp') ?>" target="_blank" class="btn btn-link">Mehr Informationen im Blog</a>

</div>