<div class="home-content-box">
  <h2 class="lead">Travaux de maintenance</h2>
  <img class="img-responsive" src="<?= $this->basePath('themes/sbvfrdmulti/images/underconstruction.jpg') ?>" width="250">
  <br/>
  <p>En raison de travaux de maintenance les fonctions suivantes ne sont pas disponibles: pré-réservations et annuler des réservations. Veuillez nous excuser pour tout désagrément causé.</p>
</div>
