<div class="home-content-box">
    <h2 class="lead">Ferienzeit, Reisezeit: Suche nach Reiseführern</h2>
    <p>Planen Sie Ihre Ferien oder eine Reise? Wir zeigen, wie Sie schnell den passenden Reiseführer dazu finden…</p>

    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib-baselbern.blogspot.ch/search/label/Tipp') ?>" target="_blank" class="btn btn-link">Mehr Informationen im Blog</a>

</div>