<div class="home-content-box">
  <h2 class="lead">Travaux de maintenance jusqu'à Dimanche, 22.11.2015, 9:00</h2>
  <img class="img-responsive" src="<?= $this->basePath('themes/sbvfrdmulti/images/underconstruction.jpg') ?>" width="250">
  <br/>
  <p>En raison de travaux de maintenance votre compte usager et les fonctions de prêt ne sont pas disponibles. La recherche n'est pas affecté. Veuillez nous excuser pour tout désagrément causé.</p>
</div>