<h1>FAQ</h1>
<nav>
    <ul>
        <li><a href="#q1">What's the fastest way to view my titles on loan?</a>
        <li><a href="#q2">Can I search a library's collection?</a></li>
        <li><a href="#q3">Can you send me titles by post?</a></li>
        <li><a href="#q4">Sometimes the link for full-text access to e-books and articles doesn't work. Why?</a></li>
        <li><a href="#q5">Can I export search results via reference management software?</a></li>
        <li><a href="#q6">Haven't found what you were looking for?</a></li>
        <li><a href="#q7">What other resources are there?</a></li>
        <li><a href="#q8">Further questions?</a></li>
    </ul>
</nav>
<br />
<dl>
    <dt><a name="q1"></a>What's the fastest way to view my titles on loan?</dt>
    <dd><p><a href="<?= $this->url('myresearch-userlogin') ?>">Log in</a>, click on My swissbib (top right).</p></dd>
    <dt><a name="q2"></a>Can I search a library's collection?</dt>
    <dd><p>Your search results can be filtered by library (on the right below refine search). Narrow your search to one specific library in advanced search. Libraries can be saved permanently as <a href="<?=$this->url('myresearch-favorite-institutions')?>"><?=$this->transEsc('mylibraries')?></a> in My swissbib.</p></dd>
    <dt><a name="q3"></a>Can you send me titles by post?</dt>
    <dd><p>Some libraries offer postal delivery to your home address or to the library of your choice for pickup. Login to your account, choose your title and click on order: pickup locations vary depending on the libraries' services. For more details see <a href="<?= $this->url('help-page', array('topic' => 'delivery')); ?>"><?= $this->transEsc('helppage.delivery') ?></a>.</p></dd>
    <dt><a name="q4"></a>Sometimes the link for full-text access to e-books and articles doesn't work. Why?</dt>
    <dd><p>Access to full-text only works within the IP-range of the university licensing its access.</p></dd>
    <dd><p>University staff and students can use VPN (<a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://mobile.unibas.ch') ?>" target="_blank">Basel</a>, <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://unibe.ch/university/campus_and_infrastructure/rund_um_computer/internetzugang/access_to_internal_resources_via_vpn/index_eng.html') ?>" target="_blank">Bern</a>) if off-campus. Search results should be filtered to Uni Basel online or Uni Bern online (on the right).</p></dd>
    <dt><a name="q5"></a>Can I export search results via reference management software?</dt>
    <dd><p>Yes. Click on the export symbol <i class="fa fa-share"></i> either from the list of your search results or from a single title.</p></dd>
    <dt><a name="q6"></a>Haven't found what you were looking for?</dt>
    <dd>
        <ul>
            <li>Expand your search to <a href="https://www.swissbib.ch" target="_blank" title="swissbib">swissbib.ch</a> (whole of Switzerland) and order from <a href="<?= $this->url('help-page', array('topic' => 'delivery')); ?>">IDS-Kurierbibliotheken</a>.</li>
            <li>Use inter library loan: order form <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/ub-hauptbibliothek/dienstleistungen/ausleihe/kurier-und-fernleihe/fernleihformular') ?>" target="_blank">UB Basel</a> / <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://unibe.ch/university/services/university_library/services/borrowing/interlibrary_loan___document_delivery/order_form/index_eng.html') ?>" target="_blank">UB Bern</a></li>
            <li>Send us your acquisition suggestion: <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/ub-hauptbibliothek/dienstleistungen/ausleihe/anschaffungsvorschlag') ?>" target="_blank">UB Basel</a> / <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://unibe.ch/university/services/university_library/services/borrowing/acquisition_suggestion/index_eng.html') ?>" target="_blank">UB Bern</a></li>
        </ul>
    </dd>
    <dt><a name="q7"></a>What other resources are there?</dt>
    <dd>
        <ul>
            <li><a href="https://www.swissbib.ch" target="_blank" title="swissbib">swissbib</a>: collections of all Swiss university libraries</li>
            <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://aleph.unibas.ch/F?CON_LNG=ENG&func=find-b-0') ?>" target="_blank" title="swissbib">Katalog IDS Basel Bern</a>: for special collections (historical material, music collections etc.) </li>
            <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://aleph.unibas.ch/F/?func=option-update-lng&file_name=find-b&p_con_lng=ENG&local_base=dsv05') ?>" target="_blank" title="swissbib">Verbundkatalog HAN</a>: manuscript index, archives etc. (Appenzell Ausserrhoden, Basel, Bern, Luzern, Solothurn und St.Gallen)</li>
        </ul>
    </dd>
    <dt><a name="q8"></a>Further questions?</dt>
    <dd><p>We are happy to help you with any questions and welcome your feedback:</p>
        <ul>
            <li>For questions concerning your account or specific titles please contact your <a href="<?= $this->basePath('Libraries') ?>" title="Liste der Institutionen">library</a>.</li>
            <li>For questions or suggestions concerning swissbib Basel Bern please use our <a href="<?= $this->url('feedback-home') ?>">contact form</a> or direct them by mail to <a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#115;&#119;&#105;&#115;&#115;&#98;&#105;&#98;&#45;&#98;&#97;&#115;&#101;&#108;&#98;&#101;&#114;&#110;&#64;&#117;&#110;&#105;&#98;&#97;&#115;&#46;&#99;&#104;">&#115;&#119;&#105;&#115;&#115;&#98;&#105;&#98;&#45;&#98;&#97;&#115;&#101;&#108;&#98;&#101;&#114;&#110; &#97;&#116; &#117;&#110;&#105;&#98;&#97;&#115;&#46;&#99;&#104;</a>.</li>
        </ul>
    </dd>
</dl>