<div class="home-content-box">
    <h2 class="lead">Linked Swissbib</h2>
    <p>
        Le projet linked.swissbib.ch vise à intégrer le métacatalogue swissbib au web sémantique par la création d’un service de données liées. Ceci implique de convertir les métadonnées de swissbib en un format sémantique, selon le modèle RDF (Resource Description Framework). La publication des données est prévue pour 2017. Apprenez-en plus sur les détails du processus grâce à 4 billets de blog.
    </p>
    <a href="http://swissbib.blogspot.ch/2016/04/swissbib-data-goes-linked-partie-1.html"
           target="_blank" class="btn btn-link" title="Link zum Blog">Plus d'informations</a>
    </div>