<div class="home-content-box">
    <h2 class="lead">Manuscrits et fonds d'archives</h2>
    <p>
        Avec l'intégration partielle du réseau «Handschriften, Archive, Nachlässe (HAN)», swissbib rend plus simple la
        découverte de fonds d'archives et de milliers de manuscrits numérisé et d'autre documents uniques.
    </p>
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib.blogspot.com/2015/11/archivbestande-und-handschriften-in.html') ?>"
       target="_blank" class="btn btn-link" title="Link zum Blog">Plus d'informations</a>
</div>