<div class="home-content-box">
    <h2 class="lead">À propos de swissbib</h2>
    <p>
        Swissbib est le catalogue de toutes les bibliothèques universitaires suisses, de la Bibliothèque nationale, de
        nombreuses bibliothèques cantonales ainsi que d'autres institutions. Il offre un accès rapide, simple et complet
        aux publications académiques en Suisse.
    </p>
    <a href="<?= $this->basePath('Libraries') ?>" class="btn btn-link" title="Liste des institutions">Institutions participantes</a>
</div>