<div class="home-content-box">
    <h2 class="lead">Licences nationales</h2>
    <p>
        En 2015, la Suisse a lancé un projet de licences nationales pour des contenus en ligne, sous l'égide du
        consortium des bibliothèques universitaires suisses. La gestion des métadonnées (au niveau des articles de
        périodiques) a été confiée à l'équipe du projet swissbib.
    </p>
    <a href="http://www.swissbib.blogspot.ch/2016/03/national-licences-and-article-metadata.html"
       target="_blank" class="btn btn-link" title="Lien vers le blogpost">Plus d'informations</a>
</div>